### ISSUE TITLE
[QUESTION] How to check if BB inventories have injection heights

### ISSUE THREAD

**Issue by jinlx** [geoschem/HEMCO#10]
## Type your question:
Hi there,

I was wondering how to check if the bomass burning inventories have injection heights. It seems that FRP of GFAS has been included information about injection heights. Does it mean QFED and GFAS has been included such information? How about GFED4 and FINN? If they don't, then how to add information of injection heights for these inventories?

Cheers,
Lixu

**Comment by yantosca** [comment]
We would recommend as a first step looking at the README files in the HEMCO data directories for each inventory:

 - ExtData/HEMCO/GFAS/v2018-09/README
 - ExtData/HEMCO/GFED4/v2018-11/README
 - ExtData/HEMCO/QFED/v2018-07/README
 - ExtData/HEMCO/FINN/v2015-02/README

You can also contact the [Emissions & Deposition Working Group](http://wiki.seas.harvard.edu/geos-chem/index.php/Emissions_and_Deposition_Working_Group) for more assistance.

**Comment by jinlx** [comment]
Hi Bob,

Thanks for getting back to me! I think the raw data doesn't have any information for injection height. It seems that we can define the injection height for FRP based emission inventories by changing xyl in the hmco configure file if I understand it right. Also, I would email emission and deposition group to see how to deal with bottom-up inventories.

Cheers,
Lixu
