### ISSUE TITLE
[QUESTION] HEMCO standalone: Error encountered in routine HCOIO_Read_Std

### ISSUE THREAD

**Issue by jinlx** [geoschem/HEMCO#100]
Hi there, I am trying to use hmco sa to output biomass burning emissions from 20180701-201801001. After setting up everything, HEMCO sa v13 runs smoothly with ifort compiler in the first few days but it stops due to error encountered in routine HCOIO_Read_Std. The error information is provided below. I am not sure how to solve the but. Ift would be great if you could provide some insights on it. 

Cheers,
Lixu
```
HEMCO WARNING: Data is treated as unitless, but file attribute suggests it is not: m s-1. File: /mnt/beegfs/atmoschem/geos-chem/ExtData/GEOS_4x5/GEOS_FP/2018
/07/GEOSFP.20180709.A1.4x5.nc
--> LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Error encountered in routine HCOIO_Read_Std!
ERROR LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
ERROR LOCATION: HCOIO_DataRead (hcoio_dataread_mod.F90)
ERROR LOCATION: ReadList_Fill (hco_readlist_mod.F90)
ERROR LOCATION: ReadList_Read (hco_readlist_mod.F90)
ERROR LOCATION: HCO_RUN (hco_driver_mod.F90)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Error in HCOIO_DATAREAD called from HEMCO ReadList_Fill: CLOUD
ERROR LOCATION: ReadList_Fill (HCO_ReadList_Mod.F90)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Error in ReadList_Fill (4) called from HEMCO ReadList_Read
ERROR LOCATION: ReadList_Read (HCO_ReadList_Mod.F90)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Error encountered in routine "Hco_Run", phase 1!
ERROR LOCATION:  -> at HCOI_SA_Run (in module HEMCO/Standalone/hcoi_standalone_mod.F90)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Error encountered in routine "HCOI_Sa_Run"!
ERROR LOCATION:  -> at HCOI_StandAlone_Run (in module HEMCO/Interfaces/hcoi_standalone_mod.F90)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by msulprizio** [comment]
I transferred this issue to the HEMCO repository since it pertains to the HEMCO standalone simulation

**Comment by lizziel** [comment]
Hi @jinlx, try a run with `Verbose` and `Warnings` both set to 3 in `HEMCO_Config.rc`. This may give more information about the source of the error.

**Comment by yantosca** [comment]
HI @jinlx, if you are using the HEMCO standalone with some extensions turned then you might have to enable met field reading.  But I think it should already be set up to do that.  The "CLOUD" field is one of the met fields.  I think that is needed for MEGAN.

**Comment by jinlx** [comment]
Thanks everyone for your inputs!
- Hi @lizziel , here is the new log file with seeting verbose and warnings to 3. It seems that it still ends up in 6th day for unknown reason.
[HEMCO.log](https://github.com/geoschem/HEMCO/files/6939298/HEMCO.log)
- Hi @yantosca , yes, I think the met was turned on. The first 5 days are running smoothly but not sure why it can't continue on 6th day. I think the last resort is to run 5 days in each job script.

**Comment by yantosca** [comment]
@jinlx: I wonder if you are hitting a memory limit on your system.  Are you using a job scheduler like SLURM, PBS, or SGE?  If so, then make sure to request enough memory for the job.

**Comment by jinlx** [comment]
Thanks Bob! You are right. I think it is related to the server itself rather than hmco sa. I end up separating into several jobs. I will close the issue right now.
