### ISSUE TITLE
[QUESTION]Is it possible to save out sector emissions in HEMCO? 

### ISSUE THREAD

**Issue by lwcugb** [geoschem/HEMCO#101]
Greetings,

I want to save out the emissions from a sector of MIX inventory (e.g. MIX_NO_IND), but we can only specify until the emission hierarchy in the HEMCO_Diagn.rc file and different sectors have the same hierarchy number.  So I am thinking it is not possible to do so, right?  I applied a factor to the base emission and just want to double-check if the factor was successfully applied.

Thanks,
Wei

**Comment by lizziel** [comment]
Hi @lwcugb, could you provide the config files you are working with and indicate what in the files you changed? If you add extension 'txt' to the HEMCO rc files you can drag and drop them into the GitHub comment box.

**Comment by lwcugb** [comment]
> Hi @lwcugb, could you provide the config files you are working with and indicate what in the files you changed? If you add extension 'txt' to the HEMCO rc files you can drag and drop them into the GitHub comment box.

[HEMCO_Config.rc.txt](https://github.com/geoschem/HEMCO/files/6927018/HEMCO_Config.rc.txt)
[HEMCO_Diagn.rc.txt](https://github.com/geoschem/HEMCO/files/6927019/HEMCO_Diagn.rc.txt)

I have attached my configure and diagnostics files. Basically, I want to overwrite the default MIX scale factor file using my own factor for future emissions. I applied the factor to each MIX sector and want to save out the emissions by sector. But the lines I added to the diagnostics file gave me the total emissions from all sectors. So, I am guessing it is not possible to save out sector emissions by simply adding some lines.

Thanks,
Wei

**Comment by msulprizio** [comment]
@lwcugb You can achieve what you describe by assigning each emission sector to a different category. The default category values are listed in [hco_gc_diagn_include.H](https://github.com/geoschem/geos-chem/blob/main/GeosCore/hcoi_gc_diagn_include.H) (e.g. Cat=1 for anthropogenic, Cat=3 for natural). You may define your own categories by simply adding new values to the Cat column in HEMCO_Config.rc. For example, for MIX_NO_* change the `1` to something like `60` for IND, `61` for POW, `62` for RES, `63` for TRA. Follow the same for the other MIX species.

```
# ExtNr	Name sourceFile	sourceVar sourceTime C/R/E SrcDim SrcUnit Species ScalIDs Cat Hier

0 MIX_NO_IND   $ROOT/MIX/v2015-03/MIX_Asia_NO.generic.025x025.nc   NO_INDUSTRY      2008-2010/1-12/1/0 RF xy kg/m2/s  NO   1/27/25/1006      60 45
0 MIX_NO_POW   $ROOT/MIX/v2015-03/MIX_Asia_NO.generic.025x025.nc   NO_POWER         2008-2010/1-12/1/0 RF xy kg/m2/s  NO   1/27/25/1006      61 45
0 MIX_NO_RES   $ROOT/MIX/v2015-03/MIX_Asia_NO.generic.025x025.nc   NO_RESIDENTIAL   2008-2010/1-12/1/0 RF xy kg/m2/s  NO   1/27/25/1006      62 45
0 MIX_NO_TRA   $ROOT/MIX/v2015-03/MIX_Asia_NO.generic.025x025.nc   NO_TRANSPORT     2008-2010/1-12/1/0 RF xy kg/m2/s  NO   1/27/25/1006      63 45
```

Then in HEMCO_Diagn.rc, you would need to add entries for each sector. For example, to save out just MIX emissions by sector:

```
# Name                   Spec   ExtNr  Cat Hier Dim OutUnit LongName

InvMIX_NO_IND            NO     0      60   45  2   kg/m2/s  NO_industrial_emission_flux_from_MIX_inventory
InvMIX_NO_POW            NO     0      61   45  2   kg/m2/s  NO_power_emission_flux_from_MIX_inventory
InvMIX_NO_RES            NO     0      62   45  2   kg/m2/s  NO_residential_emission_flux_from_MIX_inventory
InvMIX_NO_TRA            NO     0      63   45  2   kg/m2/s  NO_transportation_emission_flux_from_MIX_inventory
```

**Comment by lwcugb** [comment]
Thanks, @msulprizio. This works. Really appreciate it!! So my understanding is that the diagnostics are distinguished by species, extension, and category. If these three are the same, they will be added up. And the hierarchy number determines which inventory to use, e.g. global vs regional. Is this right?

**Comment by msulprizio** [comment]
I will close this issue for now but feel free to comment here or open a new issue if there are additional questions.
