### ISSUE TITLE
[BUG/ISSUE] Different variable name for OFFLINE_SEASALT after 20191101 with that before 20191031

### ISSUE THREAD

**Issue by 1Dandan** [geoschem/HEMCO#103]
# Report a HEMCO bug or technical issue
The variable name for OFFLINE SEASALT emission file is named as SALA_TOTAL before 20191031 while after 20191101 it is named as EmisSALA_Natural.
![image](https://user-images.githubusercontent.com/75513026/130481603-72cf4777-f15a-4cb6-aaf0-3556cb3f92dd.png)

### Steps to reproduce:g:

1.  __
2.  __
3.  __

**Run commands**

1.  __
2.  __
3.  __

### Error messages

```
add text here
```

### Your HEMCO version and runtime environment:

 - HEMCO version: __
 - Compiler version: __
 - netCDF version: __
 - netCDF-Fortran version (if applicable): __
 - Did you run on a computational cluster, on the AWS cloud: __
   - If you ran on the AWS cloud, please specify the Amazon Machine Image (AMI) ID: __
 - Are you using GEOS-Chem "out of the box" (i.e. unmodified): __
   - If you have modified GEOS-Chem, please list what was changed: __

### Input and log files to attach

 - lastbuild: __
 - HEMCO.log: __
 - HEMCO_Config.rc: __
 - HEMCO_sa_Config.rc: __ (for HEMCO standalone)
 - HEMCO_sa_Grid.rc: __ (for HEMCO standalone)
 - HEMCO_sa_Time.rc: __ (for HEMCO standalone)
 - HEMCO_sa_Spec.rc: __ (for HEMCO standalone)
 - slurm.out or any other error messages from your scheduler: __
 - Any other error messages: __

**Comment by 1Dandan** [comment]
Same problem for OFFLINE SOILNOX emission files with different variable name before 20191031 and after 20191101.
![image](https://user-images.githubusercontent.com/75513026/130486800-1401866b-a3f4-4a56-9da3-ff9233ffbc88.png)

**Comment by msulprizio** [comment]
Hi @1Dandan. Sorry we missed this issue. A similar issue was reported on the GEOS-Chem repository. See https://github.com/geoschem/geos-chem/issues/900.
