### ISSUE TITLE
[DISCUSSION] Restructuring IO capabilities

### ISSUE THREAD

**Issue by jimmielin** [geoschem/HEMCO#11]
## Overview
As part of the next major HEMCO 3.0 restructuring effort we are separating I/O (both standard and ESMF) and Regrid (A2A/messy) from the HEMCO core.

There is also a significant amount of code in `hco_interp_mod` that might be pertinent to regridding specific to `Map_A2A` & `messy`, so these should also be moved to somewhere else.

## Proposed solution
We hope to have one unified interface for IO and Regrid, eschewing the old practice of having two routines/modules `HCOIO_READ_ESMF` and `HCOIO_READ_STD`. They should be unified into `HCOIO_READ` that are implemented by different files, but only one is compiled. This could be controlled by pre-processor variables first until we figure what is best done with CESM.

`HCOIO_READ_STD` should not do the regrid. It should pass the data further up the chain, and the regridding is performed as a second step using `HCO_interp`. For std, it would call messy or a2a. For esmf it would then do nothing, because data is already on the right grid.

Allowing the code to know how to do the regrid may involve the need to create a new derived-type, say `HcoGrid` (can be based upon the current `HcoGrid`, which only holds geographical data for GEOS-Chem Classic), that describes the state of the grid the data is in. This way if we compare `HcoGrid` objects from the read with the target HEMCO grid ("intermediate grid"), if the same, then no regridding takes place. Otherwise, the regridding routine would take something like 

```fortran
! NcArr_Source is the source NcArr read from NcdfUtil
! Lct_Dest is the destination Lct data container
! Grid_Source is type HCO_Grid, describing the shape of NcArr_Source
! Grid_Dest is type HCO_Grid, describing the HEMCO working grid
call HCO_Regrid(Grid_Source, Grid_Dest, NcArr_Source, Lct_Dest)
```

We have to design `HcoGrid` type to be future-compatible with an ESMF grid specification so it must be extensible.

## Action items (Stage 1)
- [ ] Confirm HCOIO routines in standard and ESMF take in and return the same arguments
- [ ] Change HCOIO_*_Std, Esmf routines and modules to be the same names - they implement the same interface - and change dataread to call `HCOIO_Read` and `HCOIO_Write` functions; which one is compiled is dependent on pre-processor or CMake option; move these to a `IO/` folder.
- [ ] Split off interpolation routines in `HCO_Interp_Mod`, `Map_A2A` and `Messy_NCRegrid` to `Regrid/`.
- [ ] Might need to resolve circular dependencies issue; possibly split off HEMCO generic routines, i.e. `HCO_TYPES_MOD`, `HCO_ERROR_MOD` to **another** folder, e.g. `Headers/`. This is so `Regrid` and `IO` don't depend on `Core`.
- [ ] *Possibly* attach grid information for each data type to the `DataCont`, to ease development of regridding code in the future (See stage 2 action items)

## Action items (Stage 2)
- [ ] Agree on a specification for the new `HcoGrid` that is future proof.
- [ ] Build boilerplate around `HcoGrid` derived type object, possibly involving a function that does the comparison between two grids.
- [ ] Create generic `HCO_Regrid` routine that calls whatever routine in `Regrid/` is appropriate. The implementation would look something like `Convert_Spc_Units`, which has if/else statements to check the grid source and destination and choose the regridding routine as appropriate with memory allocations, etc. boilerplate around it.

**Comment by jimmielin** [comment]
Elaborating on the idea that all inputs returned from HEMCO read component, and the HEMCO state itself, should have a `HcoGrid` derived type attached to them so that the regridding routine can receive it and act accordingly:

A possible idea for the new HcoGrid derived type would be something like:

```fortran
  TYPE :: HcoGrid
     CHARACTER(LEN=255)      :: Type ! grid type (lat-lon, mapl, esmf)
     INTEGER :: IM ! x-size
     INTEGER :: JM ! y-size
     INTEGER :: LM ! z-size

     TYPE(Arr2D_Hp), POINTER :: XMID       ! mid-points in x-direction (lon)
     TYPE(Arr2D_Hp), POINTER :: YMID       ! mid-points in y-direction (lat)
     TYPE(Arr2D_Hp), POINTER :: XEDGE      ! grid edges in x-direction (lon)*
     TYPE(Arr2D_Hp), POINTER :: YEDGE      ! grid edges in y-direction (lat)*
     TYPE(Arr3D_Hp), POINTER :: PEDGE      ! pressure edges (Pa)
     TYPE(Arr2D_Hp), POINTER :: YSIN       ! sin of y-direction grid edges*
     TYPE(Arr2D_Hp), POINTER :: AREA_M2    ! grid box areas (m2)
     TYPE(Arr2D_Hp), POINTER :: ZSFC       ! surface geopotential height (m)**
     TYPE(Arr2D_Hp), POINTER :: PSFC       ! surface pressure (Pa)
     TYPE(Arr2D_Hp), POINTER :: PBLHEIGHT  ! PBL height in m
     TYPE(Arr3D_Hp), POINTER :: BXHEIGHT_M ! grid box heights (m)**
     TYPE(VertGrid), POINTER :: ZGRID      ! vertical grid description
  END TYPE HcoGrid
```

So that for our regular grids it would be just `Grid%Type = "lat-lon"`, for GEOS-Chem Classic.

In the case of GEOS-5 & GCHP, the `Grid%Type = "mapl"` will always be true for both input data returned from the `HCOIO_Read` and the HEMCO state. If this is the case, no regridding will ever be performed because it is handled by MAPL.

In the future CESM2-GC, `Grid%Type` could be `esmf`, and we could add a field, e.g. `TYPE(ESMF_GRID) :: ESMF_GRIDDATA` and ignore the fields below because the grid is then described by ESMF.

**Comment by lizziel** [comment]
Rather than use mapl and esmf and for grid%type, could there instead be a new field, such as grid%handler? I think we should stay true to the grid type field description so as not to cause confusion, since esmf and mapl are not actual grid types.

**Comment by jimmielin** [comment]
Hi Lizzie, yes it would make more sense! We should have a `hco_grid_mod.F90` with utility functions for handling all grid types (comparison comes to mind, maybe other utilities too).

I see that `hco_interp_mod.F90` is mostly pertinent to `MAP_A2A` so it can be potentially moved into `Regrid/hco_regrid_a2a.f90` or something. We probably need to have a convention to name all the IO & Regrid files.

**Comment by msulprizio** [comment]
@jimmielin Is there an updated status on this?

**Comment by jimmielin** [comment]
This is still in progress for HEMCO 3.0+. Right now CESM uses `HCOIO_Read_Std_Mod` (will be renamed to "Default Data Input Layer"). I will update with progress on implementing NCAR Parallel I/O via CDEPS (https://github.com/ESCOMP/CDEPS) soon.
