### ISSUE TITLE
[FEATURE REQUEST] Retire the CH4 wetland emissions extension

### ISSUE THREAD

**Issue by msulprizio** [geoschem/HEMCO#122]
We should retire the CH4 wetland HEMCO extension based on [Picket-Heaps et al. (2011)](https://acp.copernicus.org/articles/11/3773/2011/). Folks at Harvard are (and have been for a while) exclusively using the [JPL WetCharts](https://daac.ornl.gov/cgi-bin/dsviewer.pl?ds_id=1502) emissions. It may be confusing to users to have both options available and it is possible for users to accidentally double count wetland emissions if they turn both options on (JPL WetCharts is available via HEMCO base emissions, while CH4_Wetlands is a HEMCO extension option). 

This has been approved by Kevin Bowman and Dylan Jones, the Carbon Cycle Working Group leaders. We will proceed with retiring this extension. If users want to use this extension for research/evaluation purposes, they may revert to an older HEMCO version that still includes the option.

**Comment by yantosca** [comment]
PR #124 has been merged into the HEMCO development stream and will be included in HEMCO 3.4.0.  We can now close out this issue.
