### ISSUE TITLE
[QUESTION] Save out HEMCO restart files by custom frequency

### ISSUE THREAD

**Issue by jinlx** [geoschem/HEMCO#123]
Hi there,

For missing offline dust, biogenic VOC, and soil NO data, I realized that we need HEMCO restart files to calculate MEGAN and soil NO online. It seems that HEMCO restart files only save out when the simulation ends. I was wondering if it will influence the MEGAN and NO online caculation when there is no HEMCO restart file. If it does, I wonder how I can we set the save out frequency. I tried DiagnFreq setting in HEMCO config file but it seems that it only works for HEMCO_diagnostics output. 

Cheers,
Lixu

**Comment by lizziel** [comment]
Writing HEMCO restart files can be configured to be something other than 'End', but it requires changing the source code and recompiling. See [this](https://github.com/geoschem/HEMCO/blob/e8dfc811e161cc8b694e37985e58c27c6c97c5ec/src/Core/hco_diagn_mod.F90#L42-L47) at the top of `src/Core/hco_diagn_mod.F90`. Technically the HEMCO restart variables are part of a HEMCO diagnostics collection, hence there is code for it in the diagnostics module. It is part of a different diagnostics collection than what you program in `HEMCO_Diagn.rc` and `HEMCO_Config.rc`, hence you could not configure the output frequency like you do for other diagnostics.

To change the frequency you can adjust [this section](https://github.com/geoschem/HEMCO/blob/e8dfc811e161cc8b694e37985e58c27c6c97c5ec/src/Core/hco_diagn_mod.F90#L404-L410) of file `hco_diagn_mod.F90`, which is where the restart collection is initially defined. Variables `deltaYMD` and `deltaHMS` are the output frequency and are stored as fields within the diagnostic collection object (type `diagnCollection`). For GC-Classic they are set to very large numbers, effectively resulting in the default write at the end of the run. For ESMF models such as GEOS and GCHP they are set to 0 and 1 respectively, which translates to daily output. 

You can see the mapping between `deltaYMD` and `deltaHMS` values and a qualitative description of frequency [here](https://github.com/geoschem/HEMCO/blob/e8dfc811e161cc8b694e37985e58c27c6c97c5ec/src/Core/hco_diagn_mod.F90#L4138-L4160), which is the code that interprets the regular diagnostics frequency entry from HEMCO_Config.rc and sets the delta variables accordingly.

All that being said, whatever the extensions are using for online computations that are included in the restart file collection would be available during the run. You don't need to keep reading a restart file in beyond the initial simulation start.

**Comment by yantosca** [comment]
I will close out this issue for now.
