### ISSUE TITLE
[DISCUSSION] Building HEMCO as a submodule in GEOS-Chem and enabling standalone compile with CMake

### ISSUE THREAD

**Issue by jimmielin** [geoschem/HEMCO#13]
## Overview
We want to transition to using HEMCO as a git submodule in GEOS-Chem starting with 13.0.0. Testing efforts have begun with the 12.7.0 development source.

## Additional information
As of today HEMCO is synced to the latest `dev/12.7.0` source and can be built with GEOS-Chem in this way. Steps follow for `cmake`.

1. Get a GEOS-Chem code directory, and `rm -r HEMCO` to get rid of existing hard sources.
2. `git add -A` and `git commit`. otherwise git will complain when building submodule
3. `git submodule add git@github.com:geoschem/HEMCO.git`
4. Edit `HEMCO/CMakeLists.txt` and add
```
add_subdirectory(src)
```
Since HEMCO source is now in `HEMCO/src` and not `HEMCO`.
5. [Build GEOS-Chem using CMake as usual](http://wiki.seas.harvard.edu/geos-chem/index.php/Building_GEOS-Chem_with_CMake)

## Action items
TBD

**Comment by lizziel** [comment]
Update to build HEMCO standalone with CMake are now in the master branch. The CMake files also work with HEMCO within GEOS-Chem. I am going to be updating them to work with HEMCO in GCHP and GEOS over the next week.

**Comment by msulprizio** [comment]
This work is now done and included in GEOS-Chem 13.0.0 / HEMCO 3.0.0.
