### ISSUE TITLE
Query about "list-directed I/O syntax error, unit -5"

### ISSUE THREAD

**Issue by SadiaToma** [geoschem/HEMCO#130]
Hi,

Good morning. I was trying to update my HEMCO_Config.rc and ExtData.rc files to incorporate a newer version of the CEDS inventory along with scaling factors. However, my runs are ending with the following error message. 

"Modifying HEMCO_Config.rc
Setting CO2 concentration to 431.5 ppmv
forrtl: severe (59): list-directed I/O syntax error, unit -5, file Internal List-Directed Read"

I have the feeling like I have not updated the HEMCO_config file properly, but could not figure that out. Is there any way to move forward and deal with this kind of error? 

I am attaching my HEMCO_Config.rc and error files. I think nothing is related to the configuration since it is running with the previous HEMCO_config file.  

[HEMCO_Config.rc.txt](https://github.com/geoschem/HEMCO/files/8117303/HEMCO_Config.rc.txt)
[ExtData.rc.txt](https://github.com/geoschem/HEMCO/files/8117304/ExtData.rc.txt)
[slurm-435462.out.txt](https://github.com/geoschem/HEMCO/files/8117305/slurm-435462.out.txt)
[gchp.log.txt](https://github.com/geoschem/HEMCO/files/8117306/gchp.log.txt)
[runConfig.sh.txt](https://github.com/geoschem/HEMCO/files/8117320/runConfig.sh.txt)

I would highly appreciate it if you could help me with this. 

Thanks,
Sadia

**Comment by yantosca** [comment]
If you modified the CEDS emissions entries in HEMCO_Config.rc, doublecheck that there aren't any extraneous characters.   Same with any new scale factors you might have added.

**Comment by SadiaToma** [comment]
Hi @yantosca thanks for your suggestions. I have been trying for the last two days to find something odd, but could not proceed further. Possibly I am doing some silly mistakes related to the I/O syntax. Would you mind having a quick peek at the file to see if you can see anything inconsistent? I would highly appreciate that. I am attaching both the newer and the default version (that works) of HEMCO_Config files for your considertaion.  Thanks.

[HEMCO_Config.rc_default.txt](https://github.com/geoschem/HEMCO/files/8129426/HEMCO_Config.rc_default.txt)
[HEMCO_Config.rc_with_CEDS_SF.txt](https://github.com/geoschem/HEMCO/files/8129427/HEMCO_Config.rc_with_CEDS_SF.txt)

Thanks for your time. 

Regards,
Sadia

**Comment by SadiaToma** [comment]
Hi, 
Good morning. Although I could not solve my problem and am getting the same error, I think I can point out the specific location of the code from where the error is originating.

When I am trying to define a new scale Id ("1102")  in Line no 3543 of my HEMCO_Config.rc file for my GCHP simulations, it is causing the error **"Modifying HEMCO_Config.rc
Setting CO2 concentration to 423.9 ppmv
forrtl: severe (59): list-directed I/O syntax error, unit -5, file Internal List-Directed Read"** 

I have monthly scaling factors for each year and I want to apply that to the monthly base CEDS emission of the year 2014.
 
Line 3543: **_1102 SF_NG_CO	/home/watkin/EPPA-TAPS/Scaling_Outputs/Monthly/Annual_Interpolations/CEDS/out_paris2c_WEO2018_NPS_CLE_CH4b/$YYYY/CO-em-liquid-fuel-plus-natural-gas_CEDS_$YYYY.nc  -  $YYYY/1-12/1/0  C  xy 1 1_**

However, the simulation runs if I use a constant scaling factor instead of the NetCDF file. Example:
"**_1102 SF_NG_CO  0.5  -  $YYYY/1-12/1/0  C  xy 1 1_**"

And for my ExtData.rc file I am defining the scaleID as below:
"**_SF_NG_CO	1 N Y 0 none none - ./CEDS_EPPA_TAPS_Scaling/%y4/CO-em-liquid-fuel-plus-natural-gas_CEDS_%y4.nc 2000-01-01T00:00:00P0001-00-00T00:00:00**"

I am really not getting any clue and it would be very helpful if anyone can help. 

Thanks,
Sadia

**Comment by christophkeller** [comment]
Hi Sadia, a couple of suggestions:
1. You need to provide the variable name that you want to read from your netCDF file. This is the entry after the file name. Currently, it is set to '-'. 
2. Is your last entry indeed `1_`? If so, you should remove the underscore.
3. For the sourceTime column, I suggest you change it to `2000-2021/1-12/1/0` instead of `$YYYY/1-12/1/0`, with the year range reflecting the available years (for instance, if you have scale factors from 2010 to 2020 you would set it to `2010-2020/1-12/1/0`)
4. Your file name might be too long. If this is the case, the code should crash later on with an error saying the the file cannot be found.

**Comment by SadiaToma** [comment]
Thank you so much for your suggestions.

**Comment by yantosca** [comment]
Have you resolved your issue, @SadiaToma?
