### ISSUE TITLE
[QUESTION] CEDS README description of NMVOC categories

### ISSUE THREAD

**Issue by lorenzocostantino** [geoschem/HEMCO#147]
Hello, 

I notice that in the latest CEDS collection for GCHP (HEMCO/CEDS/v2021-06/) the README file does not contain explanations on the breakdown between the different NMVOC categories, as in previous versions.

Do you confirm that the methodology is the same as before? In particular :

... "The split between these 23 categories was done by extracting from the 0.5 degree gridded RETRO speciation files (retro_nmvoc_ratio.zip) downloaded from the HTAPv2 wiki website. Sector-specific speciation profiles were extracted for each country and, where necessary, noramlized to sum to 1. These profiles were applied to each country and sector and fuel category int eh CEDS_GBD-MAPS emissions data. The profiles are held constant over time. " ....

Thanks

lorenzo

**Comment by msulprizio** [comment]
Hi @lorenzocostantino. In the [`ceds_edit.sh`](http://geoschemdata.wustl.edu/ExtData/HEMCO/CEDS/v2021-06/scripts/CEDS_edit.sh/) included HEMCO/CEDS/v2021-06/scripts/, we have:

```
# NMVOC emissions are split into the following 23 species groups:
# VOC_id  VOC_name                     molecular weight     GEOS-Chem Species
# VOC1    alcohols                     46.2                 EOH 
# VOC2    ethane                       30                   C2H6
# VOC3    propane                      44                   C3H8
# VOC4    butanes                      57.8                 ALK4
# VOC5    pentanes                     72                   ALK4
# VOC6    hexanes_plus_higher_alkanes  106.8                ALK4
# VOC7    ethene                       28                   C2H4
# VOC8    propene                      42                   PRPE
# VOC9    ethyne                       26                   C2H2
# VOC12   other_alkenes_and_alkynes    67                   -
# VOC13   benzene                      78                   BENZ
# VOC14   toluene                      92                   TOLU
# VOC15   xylene                       106                  XYLE
# VOC16   trimethylbenzenes            120                  -
# VOC17   other_aromatics              126.8                -
# VOC18   esters                       104.7                -
# VOC19   ethers                       81.5                 -
# VOC20   chlorinated_hydrocarbons     138.8                -
# VOC21   methanal                     30                   CH2O
# VOC22   other_alkanals               68.8                 ALD2
# VOC23   ketones                      75.3                 MEK
# VOC24   acids                        59.1                 HCOOH
# VOC25   other_voc                    68.9                 -
# 
# It is assumed that isoprene (number 10) and terpenes (number 11) are not
# emitted in significant quantities by anthropogenic sources, and are not
# included in the anthropogenic split.
```

More detailed information about the NMVOCs in this inventory may be found in the reference documentation at https://doi.org/10.5194/gmd-11-369-2018.

**Comment by msulprizio** [comment]
I will close this issue for now, but please let us know if there are further questions.
