### ISSUE TITLE
[BUG/ISSUE] Parsing HEMCO_Config.rc emissions switches is not robust

### ISSUE THREAD

**Issue by lizziel** [geoschem/HEMCO#150]
Investigation of a GCHP bug (https://github.com/geoschem/GCHP/issues/225) revealed that emissions are not used if the HEMCO switch in config file `HEMCO_Config.rc` contains tabs.

For example, the following line:
`    --> HTAPv3                :       true    # 2000-2018`
is interpreted as HTAPv3 true only if all of the whitespace is spaces. Replacing it with tabs makes it be interpreted as false.

A few months ago I also noticed that including true or false after the comment character (`#`) can interfere with correct interpretation of the line.

We need to revisit how these lines in the config file are parsed to make them more robust.

**Comment by msulprizio** [comment]
This should now be resolved by PR https://github.com/geoschem/HEMCO/pull/151.
