### ISSUE TITLE
[BUG/ISSUE] Example for regional scale factors does not work

### ISSUE THREAD

**Issue by ktravis213** [geoschem/HEMCO#153]
# Report a HEMCO bug or technical issue
## Describe the bug:
I want to zero out emissions over Seoul, South Korea.  I applied the following scale factor to the mask I made for Seoul per the below example on the HEMCO guide page. 

```console
501 SCALE_SEOUL      0.0             - - - xy unitless 1 1011
1011 SEOUL_MASK  126.6/37.2/127.2/37.6                                           –      2000/1/1/0 C xy 1 1 126.6/37.2/127.2/37.6
```
I didn't see an example for this in https://hemco.readthedocs.io so maybe something has changed in the latest HEMCO.

### Expected behavior: ###
I followed this example: http://wiki.seas.harvard.edu/geos-chem/index.php/HEMCO_examples#Zero_emissions_by_country

### Actual behavior: ###
Instead of applying a scale factor to the mask domain, HEMCO crashes looking for a file to read.
```console
HEMCO ERROR: Cannot find file for current simulation time: 126.6/37.2/127.2/37 .6 - Cannot get field SEOUL_MASK. Please check file name and time (incl. time range flag) in the config. file
```

### Steps to reproduce:

Apply the mask over Seoul to any inventory, for example:
```console
0 CEDS_NO_ENE     $ROOT/CEDS/v2021-06/$YYYY/NO-em-anthro_CMIP_CEDS_$YYYY.nc            NO_ene            1750-2019/1-12/1/0 C xy kg/m2/s NO    25    **1011**    1 5
```
### Your HEMCO version and runtime environment:

 - HEMCO version: 3.4.0
### Additional context
[test4.log](https://github.com/geoschem/HEMCO/files/9084089/test4.log)
[HEMCO.log](https://github.com/geoschem/HEMCO/files/9084090/HEMCO.log)

**Comment by yantosca** [comment]
Thanks for writing @ktravis213.  We wlll look into this.  Also note, we are in the process of porting the HEMCO documentation to https://hemco.readthedocs.io, and we hope to clean up doc pages that are obsolete.

**Comment by yantosca** [comment]
Hi @ktravis213.  The problem seems to be that HEMCO was thinking that it should read the mask specification from disk because that is specified in the filename field.  I added some extra logic to routines `hco_config_mod.F90` and `hcoio_read_std_mod.F90` and that seems to fix the issue.   This is now in commit 8acf79eb17b5619fa47f4c4b2c034f82a32a78fd which is now in the **bugfix/masks** branch. 

Also tagging @jimmielin who has also made a lot of updates to HEMCO recently.

**Comment by yantosca** [comment]
@ktravis213: Also see our updated examples at https://hemco.readthedocs.io/en/latest/hco-ref-guide/more-examples.html.  We are moving the HEMCO user guide from the wiki to here.

**Comment by msulprizio** [comment]
@ktravis213 Did you ever get this working? I reported a similar issue in #286.
