### ISSUE TITLE
[BUG/ISSUE]Bug when using GEOS-FP 4x5 Met with Standalone 3.5.0-rc.1 on AWS

### ISSUE THREAD

**Issue by arianatribby** [geoschem/HEMCO#162]
# Report a HEMCO bug or technical issue

## Describe the bug:
There appears to be a problem when reading the Volcano emissions. I do not experience this problem when using Merra2 met. 

### Expected behavior: ###
I've checked that the Volcano emissions are present and the file is not empty. 

### Actual behavior: ###
Here is the print to the terminal near the error: 

```
HEMCO: Opening /home/ubuntu/ExtData/HEMCO/OFFLINE_LIGHTNING/v2020-03/GEOSFP/2019
/FLASH_CTH_GEOSFP_0.25x0.3125_2019_06.nc4                                       
HEMCO (VOLCANO): Opening /home/ubuntu/ExtData/HEMCO/VOLCANO/v2021-09/2019/06/so2
_volcanic_emissions_Carns.20190601.rc
At line 735 of file /home/ubuntu/HEMCO/rundirs/hemco_4x5_geosfp/CodeDir/src/Exte
nsions/hcox_lightnox_mod.F90
Fortran runtime error: Index '-18583' of dimension 1 of array 'inst%profile' bel
ow lower bound of 1
```

### Steps to reproduce:g:

1. Clone GCClassic and checkout a branch at release candidate 14.0.0-rc.12. 
```
git clone https://github.com/geoschem/GCClassic  
cd GCClassic
git checkout tags/14.0.0-rc.1
git branch 14.0.0.rc-1
git checkout 14.0.0-rc.1
git submodule update --init --recursive
```
2. Create a GCClassic run directory
```
cd run
./createRunDir.sh  and follow prompts
cd /path/to/GCClassic/rundir
```
3.  Compile and build GEOS-Chem Classic
```
cd build
cmake ../CodeDir -DRUNDIR=..
make -j
make -j install
cd ..
```
4. Run a GEOS-Chem Classic dry-run simulation to download data. I did not edit the default configuration files, except I changed the time period to 20190601-20190901.
```
./gcclassic --dryrun | tee log.dryrun
conda activate geo
./download_data.py log.dryrun --amazon
conda deactivate
```
5. Create HEMCO Standalone Run directory 
```
cd CodeDir/src/HEMCO/run
./createRunDir.sh and follow the prompts
```
6. Compile the Standalone 
 ```
cd /path/to/HEMCO/standalone/rundir   
cd build
cmake ../CodeDir -DRUNDIR=..
make -j
make install
cd ..
```
7. Run 
```
./hemco_standalone -c HEMCO_sa_Config.rc 
```
### Your HEMCO version and runtime environment:

 - HEMCO version: 3.5.0-rc.1
 - Compiler version: AWS AMI
 - netCDF version: AWS AMI
 - netCDF-Fortran version (if applicable): AWS AMI
 - Did you run on a computational cluster, on the AWS cloud: yes
   - If you ran on the AWS cloud, please specify the Amazon Machine Image (AMI) ID: ami-0491da4eeba0fe986
[HEMCO_sa_Spec.rc_sa_072122.txt](https://github.com/geoschem/HEMCO/files/9421411/HEMCO_sa_Spec.rc_sa_072122.txt)
[HEMCO.log_sa_072122.txt](https://github.com/geoschem/HEMCO/files/9421412/HEMCO.log_sa_072122.txt)
[HEMCO_Config.rc.gmao_metfields_sa_072122.txt](https://github.com/geoschem/HEMCO/files/9421413/HEMCO_Config.rc.gmao_metfields_sa_072122.txt)
[HEMCO_Diagn.rc_sa_072122.txt](https://github.com/geoschem/HEMCO/files/9421414/HEMCO_Diagn.rc_sa_072122.txt)
[HEMCO_sa_Config.rc_sa_072122.txt](https://github.com/geoschem/HEMCO/files/9421415/HEMCO_sa_Config.rc_sa_072122.txt)
[HEMCO_sa_Grid.4x5.rc_sa_072122.txt](https://github.com/geoschem/HEMCO/files/9421416/HEMCO_sa_Grid.4x5.rc_sa_072122.txt)

 - Are you using GEOS-Chem "out of the box" (i.e. unmodified): yes
   - If you have modified GEOS-Chem, please list what was changed:

**Comment by yantosca** [comment]
HI @arianatribby.  This looks like an out-of-bounds error in the lightning extension:
```console
At line 735 of file /home/ubuntu/HEMCO/rundirs/hemco_4x5_geosfp/CodeDir/src/Exte
nsions/hcox_lightnox_mod.F90
Fortran runtime error: Index '-18583' of dimension 1 of array 'inst%profile' below lower bound of 1
```
This is occurring here:
```F90
    ! Compute the height [km] at the top of each vertical level.
    ! Look up the cumulative fraction of NOx for each vertical level
    DO L = 1, LTOP
       ZHEIGHT = ZHEIGHT + HcoState%Grid%BXHEIGHT_M%Val(I,J,L)
       FRAC(L) = Inst%PROFILE( NINT( ( ZHEIGHT/H0 )*3200. ), MTYPE ) *0.01
    ENDDO
```
which is probably happening because `NINT( ( ZHEIGHT/H0 )*3200. )` is some weird value.    You could try printing that value out to see what it is.  Maybe we need to make sure it doesn't go below 1.

I tried building the HEMCO standalone with the debugging flags:
```console
cd build
cmake ../CodeDir -DCMAKE_BUILD_TYPE=Debug
make -j
make -j install
cd ..
```
and I was able to run without it crashing.  If you can try that too that might reveal some issue.

Also, could you attach the `HEMCO_Config.rc` file (the one from your GEOS-Chem run directory).  Thanks.
