### ISSUE TITLE
[QUESTION]How to use RCP inventory in the simulation?

### ISSUE THREAD

**Issue by jiaying002** [geoschem/HEMCO#165]
I am planning to use the RCP emission inventory from HEMCO. I noticed that the createRunDir.sh file provided seems not made for the emission inventories. I am kind of lost about what I should do to use RCP inventory in the simulation. Thank u.

**Comment by yantosca** [comment]
Thanks for writing @jiaying002.  Which simulation type are you using?  I think the RCP emissions may only be included in the full-chemistry simulations.

What you can do is to create a full-chemistry simulation run directory, and then copy the RCP entries from the fullchem `HEMCO_Config.rc` file to your `HEMCO_Config.rc` file.  You'll also need to copy the switches that turn RCP options on or off.

Also, we have recently migrated the HEMCO manual to from the wiki to https://hemco.readthedocs.io.  You will find more information about setting up the `HEMCO_Config.rc` file there.

**Comment by yantosca** [comment]
Also tagging @Jourdan-He
