### ISSUE TITLE
[QUESTION]How to translate the code in geoschem.run from SLURM to PBS

### ISSUE THREAD

**Issue by jiaying002** [geoschem/HEMCO#166]
My server uses PBS schedular, while the code provided (geoschem.run) was for SLURM. I tried translating the code from SLURM to PBS, but I failed. I cannot find all the code I need from google, and the one I found is still doubtful. It would be best if someone could guide me on where to find the translated version.

**Comment by yantosca** [comment]
Thanks for writing @jiaying002. Have you looked at this page?  It is a pretty good description:
https://www.marquette.edu/high-performance-computing/pbs-to-slurm.php

For SLURM we use e.g.  `#SBATCH -c 8` to request 8 cores.  You can replace that with `#PBS -l nodes=1:ppn=8`, which will request 8 cores on 1 node.

Finally, in the PBS batch script, you'll have to change
```bash
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
```
to
```bash
export OMP_NUM_THREADS=8  # or however many cores you are using.
```

**Comment by yantosca** [comment]
Also tagging @Jourdan-He

**Comment by lizziel** [comment]
Hi @jiaying002, you could also take a look at the template run script for GCHP and adapt it for GEOS-Chem Classic. It includes PBS as one of the schedulers. See file [here](https://github.com/geoschem/geos-chem/blob/main/run/GCHP/runScriptSamples/gchp.batch_job.sh).

**Comment by jiaying002** [comment]
Thank u!

**Comment by jiaying002** [comment]
Hi, sorry for reopening this case. I tried to change the SLURM to PBS and here is the geoschem.run file I modified. 
[geoschem.run.txt](https://github.com/geoschem/HEMCO/files/9928593/geoschem.run.txt)
Then, I got an error like this: 
![image](https://user-images.githubusercontent.com/113654537/199722485-1d52d3f1-807f-418d-ac68-67f1ecf7a74e.png)
I am wondering is there anything wrong with my code?

**Comment by jiaying002** [comment]
Sorry for bothering you again. I have been struggling for days. Would you please give me some clues? @yantosca @lizziel

**Comment by yantosca** [comment]
@jiaying002: We are not as familiar with PBS as our cluster uses SLURM.  Is there anyone at your institution who handles IT support?

**Comment by yantosca** [comment]
Closing out this issue
