### ISSUE TITLE
[QUESTION] What do existing cat numbers typically indicate?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/HEMCO#17]
Hi there,

Previously I posted a question on [how HEMCO processes same/different cat and/or hier](https://github.com/geoschem/HEMCO/issues/8). One of the replies I received is "In the example above, the MIX_NO_* are not different inventories, but are different sectors of anthropogenic. Therefore they get put into category 1." So I know Cat=1 represent anthropogenic emissions.

Recently I reviewed the contents in the default HEMCO_Config.rc file. I would be grateful if you help me confirm the following correspondence.
- Cat=1: anthropogenic 
- Cat=2:
- Cat=3: natural
- Cat=10: ship
- Cat=20: aircraft

I saw Cat=2 in DICE_Africa but didn't realise its meaning.

Thanks in advance for your help.

Yours faithfully,
Fei

**Comment by yantosca** [comment]
Cat=2 is biofuel.  All the other cats you mentioned are correct.

**Comment by yantosca** [comment]
Also note: some inventories don't separate between anthro & biofuel & trash emissions so you will see either 1/2 or 1/2/12.  This means put all the emissions into anthro (cat=1) and zero the other categories (2=biofuel, 12=trash).

**Comment by FeiYao-Edinburgh** [comment]
Thanks for answering!

> Cat=2 is biofuel. All the other cats you mentioned are correct.

I have seen that you have put this when explaining [Cat in HEMCO User Guide](http://wiki.seas.harvard.edu/geos-chem/index.php/The_HEMCO_User%27s_Guide#Base_emissions). Thanks!

**Comment by lizziel** [comment]
You can always see the full category mapping for each version in file [GeosCore/hcoi_gc_diagn_include.H](https://github.com/geoschem/geos-chem/blob/master/GeosCore/hcoi_gc_diagn_include.H) that ships with the code. For example:

```
  INTEGER, PARAMETER :: CATEGORY_ANTHRO        = 1
  INTEGER, PARAMETER :: CATEGORY_NATURAL       = 3
  INTEGER, PARAMETER :: CATEGORY_BIOGENIC      = 4
  INTEGER, PARAMETER :: CATEGORY_BIOMASS       = 5
  INTEGER, PARAMETER :: CATEGORY_SHIP          = 10
  INTEGER, PARAMETER :: CATEGORY_TRASH         = 12
  INTEGER, PARAMETER :: CATEGORY_AIRCRAFT      = 20
  INTEGER, PARAMETER :: CATEGORY_VOLCANO       = 50
  INTEGER, PARAMETER :: CATEGORY_VOLCANO_ERUPT = 51
  INTEGER, PARAMETER :: CATEGORY_VOLCANO_DEGAS = 52
```

Also beware that since biofuels is now lumped with other categories in inventories the biofuel category (2) is being removed (hence not in the above list).

**Comment by FeiYao-Edinburgh** [comment]
@lizziel Many thanks!
