### ISSUE TITLE
[BUG/ISSUE] HCO_MISSVAL is incorrect for GCHP/GEOS which use MAPL

### ISSUE THREAD

**Issue by lizziel** [geoschem/HEMCO#172]
HEMCO assigns parameter `HCO_MISSVAL` (-1e31 float) to denote missing values. If HEMCO handles file read, all missing value grid cells are assigned value `HCO_MISSVAL` and those grid cells are later skipped during regrid interpolation. During HEMCO run, missing data are then specially handled during scaling and masking.

This works for models in which HEMCO handles the file read and regridding, but not for other models if they assign a different value to missing data. This is the case for GCHP and GEOS which use MAPL's missing value parameter `MAPL_UNDEF`, equal to 1e15 float. A temporary kludge was put in back in 2017 for masking in GCHP, but was not extended to scale factors, and mostly went unused because MAPL did not use the `_FillValue` attribute to identify missing values. Instead, MAPL expected missing values to have data values 1e15 in the input files as regular data or assumed `_FillValue` was 1e15.

The fix is to set `HCO_MISSVAL` to the `MAPL_UNDEF` value in HEMCO. A separate fix will be applied to MAPL to identify missing values from netCDF `_FillValue` attribute without any assumption of what that value is.

This issue is fixed HEMCO in https://github.com/geoschem/HEMCO/pull/171. 

Heads up @jimmielin that we should keep an eye out for whether there are any missing value handling issues in CESM or WRF-GC.

**Comment by jimmielin** [comment]
Thanks @lizziel. Copying @fengx7 for WRF-GC as well. We follow the handling in the GEOS-Chem Classic code as we use the same libraries so hopefully we won't have to do anything extra to be consistent with other model(s).

**Comment by lizziel** [comment]
As long as we are using HEMCO to read and regrid we should be good.

**Comment by msulprizio** [comment]
The fix for this is now merged (see https://github.com/geoschem/HEMCO/pull/171). I will close out this issue.
