### ISSUE TITLE
[BUG/ISSUE] HEMCO version in HCO_ERROR_MOD is not updated

### ISSUE THREAD

**Issue by jimmielin** [geoschem/HEMCO#176]
# Report a HEMCO bug or technical issue
I just noticed that the `HCO_VERSION` variable in `HCO_ERROR_MOD` is not being kept up-to-date with the newest HEMCO releases:

```fortran
CHARACTER(LEN=12), PARAMETER, PUBLIC :: HCO_VERSION = '3.0.0'
```

e.g., https://github.com/geoschem/HEMCO/blob/dev/3.6.0/src/Core/hco_error_mod.F90

This is very minor but maybe we could update it during the release process. Unfortunately it can't be updated using `cmake` (I believe that's what GEOS-Chem classic does?) because CESM's build system does not use `cmake`. So maybe this has to be done manually.

Thanks!
Haipeng

**Comment by msulprizio** [comment]
Thanks for reminding us about this @jimmielin. I updated the version for 3.6.0 and added a comment in `CMakeLists.txt` to remind us to update it in `hco_error_mod.F90` as well so we don't forget in the future. This is currently in the `dev/3.6.0` branch:

https://github.com/geoschem/HEMCO/blob/fc72f250bc1e4b88033a500029566b4ea2646023/CMakeLists.txt#L4-L5
