### ISSUE TITLE
[QUESTION] GFED bioburning emissions for 2020-2021 

### ISSUE THREAD

**Issue by arianatribby** [geoschem/HEMCO#177]
Hi, I am running GEOSChem/HEMCO standalone on AWS. I noticed that GFED4 bioburning emissions are not available for 2020-2021 on AWS or on Wash U ExtData. Do you have an idea of when they might be available? Thanks!

**Comment by yantosca** [comment]
Thanks @arianatribby.  We get emissions from developers, so this might be a more apropos question for the GEOS-Chem Emissions Working Group.  Tagging @eamarais @jaegle

Also tagging @Jourdan-He @SaptSinha

**Comment by msulprizio** [comment]
Hi @arianatribby. We have not heard back from the Emissions Working Group on updating GFED. You are welcome to ask the email list (geos-chem-emissions [at] g.harvard.edu) to see if anyone is working on this or plans to work on it.
