### ISSUE TITLE
Set emissions to turn off after a designated time period[QUESTION]

### ISSUE THREAD

**Issue by JbourJabber** [geoschem/HEMCO#179]
Does HEMCO allow for users to set emissions to turn off after a designated time period? For example, I am hoping to configure HEMCO to turn off emissions after the first month of the job. 

Thanks in advance!

**Comment by yantosca** [comment]
Thanks @JbourJabber for writing. You should be able to use the HEMCO `R` time cycle flag, which will only read data if it is within a certain time range.  For more information, see the [Base Emissions section at hemco.readthedocs.io](https://hemco.readthedocs.io/en/stable/hco-ref-guide/hemco-config.html#base-emissions).

**Comment by yantosca** [comment]
Also tagging @Jourdan-He and @SaptSinha for reference

**Comment by lizziel** [comment]
Note that this only works for GC-Classic.

**Comment by yantosca** [comment]
Closing out this issue
