### ISSUE TITLE
[FEATURE REQUEST] Consolidate VERBOSE and WARNINGS print options

### ISSUE THREAD

**Issue by lizziel** [geoschem/HEMCO#180]
This feature request is to make the HEMCO print options more intuitive by consolidating the `VERBOSE` and `WARNINGS` settings in `HEMCO_Config.rc`. The default is to set `VERBOSE` to 0 and `WARNINGS` to 1, but each of these settings can be any integer up to 3. The differences between these settings is not intuitive so we generally recommend users simply set them both to 3 if debugging. It would be better to come up with a simpler system such as making a single verbose option that is either on or off.

Tagging @christophkeller

**Comment by yantosca** [comment]
I've looked into the HEMCO code.  Most of the verbose printout is toggled by the function `HCO_IsVerb`.  So it should be pretty easy to change the front-end to make `Verbose: true` and then modify `HCO_IsVerb` accordingly.  I will create a draft PR shortly.

**Comment by yantosca** [comment]
The corresponding GEOS-Chem PR is https://github.com/geoschem/geos-chem/pull/1549

**Comment by yantosca** [comment]
We can close this issue since PR #182 has been merged into the 14.2.0 development stream.
