### ISSUE TITLE
[QUESTION] Ensure consistent emission flux from GFED4 daily across resolution in GCHP?

### ISSUE THREAD

**Issue by 1Dandan** [geoschem/HEMCO#181]
## Problem Description
Hi, I noticed different emission fluxes across resolution in GCHP for GFED4 daily and I think it is related the way GFED4 daily is implemented in HEMCO.

Based on my understanding, the GFED4 daily emissions are calculated in HEMCO by multiplying GFED4 monthly emission by daily scaling factors. However, both monthly emissions and daily scaling factors are read and remapped by MAPL ExtData. That means the daily scaling factors are conservatively regridded before they are passed to HEMCO. 

Regridding both monthly mean emissions and daily scaling factors and then multiply them to obtain daily emission fluxes will not ensure same emission fluxes across resolution. Monthly mean emission fluxes are the same but daily emission fluxes will be very different. Multiplying them first and then regridding can guarantee the same daily emission fluxes across resolution. 

I am wondering if there is a way to implement the latter by first multiplying and then regridding? Or should we just calculate daily emission fluxes offline and then pass them as emission inputs directly?

**Comment by yantosca** [comment]
Thanks @1Dandan.  For this reason we recommend using the `OFFLINE_BIOMASS` option with GCHP.  I think this is the only way you can ensure consistent emissions.

Tagging @sdeastham @Jourdan-He @SaptSinha

**Comment by 1Dandan** [comment]
Hi, just to bring it into attention again, using the spatially different scaling factor for daily or 3-hourly GFED emissions for biomass burning emissions are problematic, not only for GCHP but generally for GEOS-Chem including GCC as well. 

Because the way GFED is implemented in GEOS-Chem as a emission extension, daily GFED was produced by multiply monthly GFED4 with daily scaling factors. When they are both going into GEOS-Chem HEMCO, they would first be regridded to simulation resolution, and then be multiplied. As a matter of math, the average of multiplication of factors would not equal to the multiplication of averaged factors. 

And thus to ensure consistent emission flux, it is needed to multiply monthly GFED and daily scaling factor first to obtain daily GFED emissions and then feed that into GEOS-Chem. The same truth applies to 3-hourly GFED emissions, and also any emissions that use spatially different scaling factors.
