### ISSUE TITLE
Whether HEMCO diagnostic output is  before or after the scale factor applied?

### ISSUE THREAD

**Issue by hgrhgy** [geoschem/HEMCO#185]
I am confused about whether the variable of `EmisCO2_FossilFuel` in  HECMO diagnositic output file is after or before applying the scale factor. The related settings of  HEMCO_Config.rc and HEMCO_Diagn.rc are listed below. And, is the values of the variable related to the diagnostics frequence `DiagnFreq` in HEMCO_Config.rc file?  Averaged or instantaneous or something else?

For example, the HEMCO_Config.rc:
```console
...
(((FOSSIL_ODIAC
0 FOSSILCO2_ODIAC   $ROOT/CO2/v2019-12/FOSSIL/ODIAC_CO2.monthly.generic.1x1.nc   CO2 2000-2018/1-12/1/0 C xy kg/m2/s CO2   40/41/80 1 2
0 FOSSILCO2FF_ODIAC -                                                            -   -                  - -  -       CO2ff 40/41/80 1 2
)))FOSSIL_ODIAC
...
```
and the HEMCO_Diagn.rc:
```sh
EmisCO2_Total         CO2      0   -1   -1   3  kg/m2/s  CO2_total_emissions
EmisCO2_FossilFuel     CO2      0    1   -1   3  kg/m2/s  CO2_fossil_emissions
EmisCO2_Ocean         CO2      0    2   -1   2  kg/m2/s  CO2_ocean_emissions
EmisCO2_BalBiosph     CO2      0    3   -1   2  kg/m2/s  CO2_balanced_biosphere
misCO2_NetTerrExch   CO2      0    5   -1   2  kg/m2/s  CO2_net_terrestrial_exchange
EmisCO2_Ship          CO2      0    6   -1   2  kg/m2/s  CO2_ship_emissions
EmisCO2_Aviation      CO2      0    7   -1   3  kg/m2/s  CO2_aviation_emissions

```

**Comment by msulprizio** [comment]
I believe the emissions diagnostic output does not include the application of scale factors and masks. To check this, you could run a short (e.g. 1-hr) simulation with and without applying the scale factors to see if the output changes.

The [`DiagnFreq` option](https://hemco.readthedocs.io/en/stable/hco-ref-guide/hemco-config.html?highlight=diagnfreq#cmdoption-arg-DiagnFreq) specifies how often the HEMCO diagnostic file will be written to disk. By default, fields are averaged over that time period as specified in hco_diagn_mod.F90:

https://github.com/geoschem/HEMCO/blob/344429fbe2ac9b4f1262aa03a95bf3cad5dd02e0/src/Core/hco_diagn_mod.F90#L1091-L1095

For manual diagnostics, that can be changed by specifying 'OutOper' when calling 'Diagn_Create`:

https://github.com/geoschem/HEMCO/blob/344429fbe2ac9b4f1262aa03a95bf3cad5dd02e0/src/Core/hco_diagn_mod.F90#L820-L823

**Comment by hgrhgy** [comment]
I have tried to run the simulation with and without applying the scale factors, the output diagnostics are different. 
https://github.com/geoschem/HEMCO/blob/344429fbe2ac9b4f1262aa03a95bf3cad5dd02e0/src/Core/hco_diagn_mod.F90#L1964-L1970
It seems the value of diagnostics is sumed up and stored in the unit kg/m2, and divided the time factor when outputting. The value added to the diagnostics may have been applied the factor already. But I can't find where and when the value of diagnostics is sumed up.
https://github.com/geoschem/HEMCO/blob/344429fbe2ac9b4f1262aa03a95bf3cad5dd02e0/src/Core/hco_diagn_mod.F90#L3145-L3154
