### ISSUE TITLE
[DISCUSSION] HCOIO_Read_Std_Mod

### ISSUE THREAD

**Issue by jimmielin** [geoschem/HEMCO#19]
## Overview
There seems to be a lot of extra routines in `HCOIO_Read_Std_Mod` compared to the ESMF version.

**HCOIO_Read_Std_Mod**:
```fortran
  PUBLIC  :: HCOIO_ReadOther
  PUBLIC  :: HCOIO_CloseAll
#if !defined(ESMF_)
  PUBLIC  :: HCOIO_read_std
!
! !PRIVATE MEMBER FUNCTIONS:
!
  PRIVATE :: GET_TIMEIDX
  PRIVATE :: Check_AvailYMDhm
  PRIVATE :: prefYMDhm_Adjust
  PRIVATE :: Set_tIdx2
  PRIVATE :: IsClosest
  PRIVATE :: GetIndex2Interp
  PRIVATE :: GetWeights
  PRIVATE :: YMDhm2hrs
  PRIVATE :: Normalize_Area
  PRIVATE :: SrcFile_Parse
  PRIVATE :: SigmaMidToEdges
  PRIVATE :: CheckMissVal
  PRIVATE :: GetArbDimIndex
#endif
  PRIVATE :: HCOIO_ReadCountryValues
  PRIVATE :: HCOIO_ReadFromConfig
  PRIVATE :: GetDataVals
  PRIVATE :: GetSliceIdx
  PRIVATE :: FillMaskBox
  PRIVATE :: ReadMath
```

**HCOIO_Read_ESMF_Mod**
```fortran
#if defined(ESMF_)
  PUBLIC  :: HCOIO_Read_ESMF
```

Could any of the STD mod routines be moved to somewhere else? Some of these are basically managing IO stuff that is handled by MAPL in GCHP, but they may also be useful for the CESM implementation. Moving them to a more generic component (HCOIO helpers?) would allow less duplication of code as I think the CESM Parallel IO-based interface will be based upon the standard HCOIO interface quite a bit, and 4.7k lines of code is quite a lot of stuff to duplicate.

## References
The only public entry points to the HCOIO_Read_* routines in HEMCO are the following:
```
Searching 114 files for "use HCOIO_Read_Std_Mod"

src\Core\hco_readlist_mod.F90:
  406  !
  407      USE HCOIO_DataRead_Mod, ONLY : HCOIO_DataRead
  408:     USE HCOIO_Read_Std_Mod, ONLY : HCOIO_ReadOther
  409:     USE HCOIO_Read_Std_Mod, ONLY : HCOIO_CloseAll

src\Core\hcoio_dataread_mod.F90:
  169      USE HCOIO_READ_ESMF_MOD,  ONLY : HCOIO_READ_ESMF
  170  #else
  171:     USE HCOIO_READ_STD_MOD,   ONLY : HCOIO_READ_STD
  172  #endif
  173  !

3 matches across 2 files
```
So shuffling the internal routines around should be OK for compatibility.

After #11 which aims to unify the subroutine calls, maybe it would be nice to clean up all the calls to `ReadOther` `CloseAll` etc., maybe adding a cleanup routine to each IO component so they can free up the file handles (standard) or do nothing (MAPL).

**Comment by lizziel** [comment]
I am going to tackle this starting this week. If there is other information related to it that you added to other github issues in this or other repos let me know.

**Comment by yantosca** [comment]
The only thing I added was https://github.com/geoschem/HEMCO/pull/31, which is a quick bug fix for the dry-run.  I don't intend on touching anything else in HEMCO in the near future.

**Comment by lizziel** [comment]
Sorry, that question was aimed at @jimmielin. But thanks for the update on that since it does touch this file!

**Comment by jimmielin** [comment]
Hi @lizziel, I don't have any new updates on this. I will be looking into other parts of the HEMCO code to implement an intermediate grid functionality and ask for everyone's feedback during MDS. Thanks for helping with this!

**Comment by lizziel** [comment]
This update is complete in commit  https://github.com/geoschem/HEMCO/commit/b902b2385738b402e72432f595bd88d8aa4845de. Additional work to clean up subroutine calls will be ongoing.
