### ISSUE TITLE
[FEATURE REQUEST] State in readthedocs what numerical values in the time slice entry do

### ISSUE THREAD

**Issue by eamarais** [geoschem/HEMCO#200]
Name: Eloise Marais
Institution: UCL

In the HEMCO readthedocs, I couldn't find information about the utility of the value "3" for the lightning NOx emissions. Would it be possible to state what this "3" stands for? My impression is that it means "every 3 hours", but it's only applied to lightning and not to any other files that are 3-hourly like boundary conditions for nested grids and some meteorological variables.

**Comment by yantosca** [comment]
Thanks @eamarais for bringing this up.  We can add this for HEMCO 3.7.0 / GC 14.2.0 documentation.

**Comment by yantosca** [comment]
@eamarais: I looked it up on the source code.  So the dimension number is used to tell the HEMCO `Diagn_Create` routine the dimensionality of the diagnostic:

1. Scalar
2. lon-lat
3. lon-lat-lev

I'll push an update to the documentation that will go into the "latest" version of ReadTheDocs now, and which will go into the "stable" version when HEMCO 3.7.0 and GC 14.2.0 ship.

**Comment by yantosca** [comment]
Oops, I think that wasn't the 3 you were asking about.  

So I looked into the source code again and found this:
```F90
    !========================================================================
    ! Set time cycling behaviour. Possible values are:
    ! - "C"   : cycling <-- DEFAULT
    ! - "CS"  : cycling, skip if not exist
    ! - "CY"  : cycling, always use simulation year
    ! - "CYS" : cycling, always use simulation yr, skip if not exist
    ! - "R"   : range
    ! - "RA"  : range, average outside
    ! - "RF"  : range, forced (error if not in range)
    ! - "RFY" : range, forced, always use simulation year
    ! - "RFY3 : range, forced, always use simulation year, 3-hourly
    ! - "RY"  : range, always use simulation year
    ! - "E"   : exact, read/query once
    ! - "EF"  : exact, forced (error if not exist), read/query once
    ! - "EFY" : exact, forced, always use sim year
    ! - "EFYO": exact, forced, always use sim year, read once
    ! - "EC"  : exact, read/query continuously (e.g. for ESMF interface)
    ! - "ECF" : exact, forced, read/query continuously
    ! - "EY"  : exact, always use simulation year, read/query once
    ! - "A"   : average
    ! - "I"   : interpolate
    ! - "ID"  : interpolate, discontinuous dataset
    !========================================================================
```
so indeed the 3 in `RFY3` means data is read every 3 hours.  I'll update this in the doc as well.

**Comment by yantosca** [comment]
This has now been updated in: https://hemco.readthedocs.io/en/latest/hco-ref-guide/hemco-config.html#base-emissions

**Comment by eamarais** [comment]
Thanks Bob! Very helpful.
