### ISSUE TITLE
Update to include recent Volcanic emissions

### ISSUE THREAD

**Issue by kelaar** [geoschem/HEMCO#216]
### Background

Currently the volcanic emissions available to HEMCO end on January 1, 2022.

### Feature Request

Would it be possible to update the volcanic database to include data until at least January 1, 2023?

thanks,

Aaron van Donkelaar
Washington University in St. Louis

**Comment by msulprizio** [comment]
@kelaar This should not be a problem assuming that the latest emissions are at GMAO. @christophkeller Can you confirm if you have the latest emissions on Discover? If so, @lizziel or I can transfer them over.

**Comment by kelaar** [comment]
Thanks @msulprizio!  Let me know if there is any assistance I can provide.

Aaron

**Comment by kelaar** [comment]
Has there has been any update about the availability of the volcanic emissions on Discover?  I noticed @christophkeller  wasn't included in the list of participants on this thread, and wanted to make sure he had received your query.

thanks,

Aaron

**Comment by msulprizio** [comment]
I pinged @christophkeller above but perhaps he has not seen it. I will email him directly.

**Comment by kelaar** [comment]
Thanks Melissa!

**Comment by christophkeller** [comment]
Hi everyone,
I just heard back from Pete Colarco and Simon Carn, who provide the input files. Pete has files through 2022 and I can share them with you. Simon also has data up to June 2023, and I can ask Pete to convert them to the correct format. 
Going forward, I suggest we try to update the files on a regular schedule. Is once a year good enough? I could set this up with Simon and Pete.

**Comment by christophkeller** [comment]
The updated emission files through 2022 are here: https://gmao.gsfc.nasa.gov/gmaoftp/geoscf/volcano_so2/v202302/

Also, Nick Krotkov asks to use the following GES DISC references for the volcano emissions:

Explosive eruptions:
Simon Carn (2022), Multi-Satellite Volcanic Sulfur Dioxide L4 Long-Term Global Database V4, Greenbelt, MD, USA, Goddard Earth Science Data and Information Services Center (GES DISC), Accessed: [Data Access Date], https://doi.org/10.5067/MEASURES/SO2/DATA405
 
Degassing volcanos (and anthropogenic point source SO2 emissions):
Vitali Fioletov, Chris A. McLinden, Debora Griffin, Ihab Abboud, Nickolay Krotkov, Peter J. T. Leonard, Can Li, Joanna Joiner, Nicolas Theys, and Simon Carn (2022). Edited by Peter Leonard, Greenbelt, MD, USA, Goddard Earth Science Data and Information Services Center (GES DISC), Accessed: [Data Access Date], https://doi.org/10.5067/MEASURES/SO2/DATA406

**Comment by msulprizio** [comment]
Thanks @christophkeller! We will work on implementing these latest emissions into 14.3.0. 

@kelaar Feel free to start working with the updates files on your end at any time.

**Comment by kelaar** [comment]
Thanks @christophkeller and @msulprizio!  I've downloaded the files and will start using them shortly.

**Comment by yantosca** [comment]
@kelaar @msulprizio @christophkeller: We have merged PR #2198, which adds extra years of volcano emissions thru 2022 into the GEOS-Chem 14.4.0 development stream.  This will ship with the 14.4.0 release.  We can now close out this issue.  Thanks for your patience.

**Comment by kelaar** [comment]
Earlier on in this thread, @christophkeller suggested updating the volcanic emission files on a regular schedule.  Is that still the plan?  I'm preparing for a 2023 run, and would like to know if the corresponding volcanic emission files are already available, or if this is something that can be provided.  Let me know if you'd like me to email Christoph directly. Thanks!

**Comment by yantosca** [comment]
@kelaar, could you open a new issue for this?  Thanks.

**Comment by kelaar** [comment]
Thanks @christophkeller.  As per @yantosca's request, I've moved this thread to: https://github.com/geoschem/HEMCO/issues/272.

@yantosca: done.
