### ISSUE TITLE
[DISCUSSION] Organize extensions folder

### ISSUE THREAD

**Issue by jimmielin** [geoschem/HEMCO#22]
The HEMCO extensions folder may be restructured in the future. Please use this thread for discussion.

## Potential working items:
* Extension template
* Git submodules? Subfolders by extension or by process (`aerosol`, `dust`, `deposition`, ...)
* Ensemble needs (extensions calling each other, process?)
* External collaboration with extensions

**Comment by msulprizio** [comment]
@lizziel may have plans to work on this as part of HEMCO 3.0+ development. Feel free to elaborate here, Lizzie.

**Comment by lizziel** [comment]
I was only going to work in HEMCO Core for restructuring, at least in HEMCO 3. But good to start a discussion!

We do not have plans to break out extensions into git submodules since we'd end up with single file repos, probably more trouble than it is worth?
