### ISSUE TITLE
Question on the unit of emission factors in HEMCO GFED extension

### ISSUE THREAD

**Issue by fengx7** [geoschem/HEMCO#222]
### Name and Institution (Required)

Name: Xu Feng
Institution: Harvard University

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://hemco.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://hemco.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://hemco.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/HEMCO/issues)

### Description of your issue or question

For the latest version HEMCO (3.6.2), I've found an issue with the HEMCO GFED extension. In the file "hcox_gfed_include_gfed4.H", the units of emission factors for Higher Alkanes (ALK4) and Higher Alkenes (part of PRPE) are assumed to be kgC kg-1 dry matter (DM) burned. It did an additional unit conversion for the two species from kgC kg-1 to kg (species) kg-1. See details below.
```F90
ALK4 (Higher_Alkanes) - convert from kgC to kg
GFED4_SPEC_NAME(2)="ALK4"
Inst%GFED4_EMFAC(2,1)=5.50E-05_hp * 58.12_hp/(4.3_hp*12.0_hp)
Inst%GFED4_EMFAC(2,2)=3.49E-04_hp * 58.12_hp/(4.3_hp*12.0_hp)
Inst%GFED4_EMFAC(2,3)=2.25E-04_hp * 58.12_hp/(4.3_hp*12.0_hp)
Inst%GFED4_EMFAC(2,4)=7.20E-05_hp * 58.12_hp/(4.3_hp*12.0_hp)
Inst%GFED4_EMFAC(2,5)=7.20E-05_hp * 58.12_hp/(4.3_hp*12.0_hp)
Inst%GFED4_EMFAC(2,6)=3.40E-04_hp * 58.12_hp/(4.3_hp*12.0_hp)_ 

! PRPE (C3H6 + Higher_Alkenes)
GFED4_SPEC_NAME(6)="PRPE"
Inst%GFED4_EMFAC(6,1)=7.90E-04_hp + 1.33E-04_hp * 42.08_hp/(3.0_hp*12.0_hp)
Inst%GFED4_EMFAC(6,2)=1.13E-03_hp + 3.85E-04_hp * 42.08_hp/(3.0_hp*12.0_hp)
Inst%GFED4_EMFAC(6,3)=6.10E-04_hp + 3.69E-04_hp * 42.08_hp/(3.0_hp*12.0_hp)
Inst%GFED4_EMFAC(6,4)=6.40E-04_hp + 2.67E-04_hp * 42.08_hp/(3.0_hp*12.0_hp)
Inst%GFED4_EMFAC(6,5)=3.05E-03_hp + 2.27E-04_hp * 42.08_hp/(3.0_hp*12.0_hp)
Inst%GFED4_EMFAC(6,6)=6.80E-04_hp + 3.33E-04_hp * 42.08_hp/(3.0_hp*12.0_hp)_
```
But I checked the original file of emission factors from GFED website [link](https://www.geo.vu.nl/~gwerf/GFED/GFED4/ancill/GFED4_Emission_Factors.txt), it shows that the emission factors for all species are in unit of g species per kg DM burned. And I also checked the [code](https://www.geo.vu.nl/~gwerf/GFED/GFED4/ancill/code/) for offline calculations provided by GFED website, it didn't make any unit conversion for the two species.

I'm wondering why the units are assumed to be kgC kg-1 for the two species in HEMCO. And this unit conversion will increase the ALK4 and PRPE by about 12% to 17%. 

Thank you for checking this!

**Comment by fengx7** [comment]
> Hi all. I'm copying my original response here for the records:
> 
> > From the commit history, it looks like the original comment for ALK4 (Higher_Alkanes) said “already in kgC” in hcox_gfed_include_gfed4.H. See [aeb331a](https://github.com/geoschem/HEMCO/commit/aeb331af2aa6f2d69fe0db1cafc783060f7e7f78).
> > This seems to have also been the case for higher alkenes. See this commit [72c460f](https://github.com/geoschem/HEMCO/commit/72c460f17bf9cb108c892e73e7e94b49439ee389).
> 
> When implementing the updates for removal of carbon units, I went off of the original comments in the code. I would defer to the Emissions and/or Surface-Atmosphere Exchange Working Groups. I am tagging @dylanbm for any thoughts, but others may chime in as well.

Thank you, Melissa!

**Comment by dylanbm** [comment]
Based on Xu's description this sounds to me like a bug to be fixed. I have asked the other surface/atmosphere WG co-chairs and the emission WG chairs to reply here if they have any info to the contrary.

**Comment by fengx7** [comment]
> Thanks @eamarais, @dylanbm, and @fengx7. Would someone be able to make a pull request with the proper code? We can get this into a patch version like 14.2.1 which is in prep.

Thank you @yantosca @msulprizio @dylanbm, and @eamarais. I would defer to your decision and make a pull request.

**Comment by pkasibhatla** [comment]
Sorry for being late to this .. I have been out .. but it is not clear to me that this is an error. While the original species emission factors are in g compound per kg DM burned, one has to convert to carbon units to correctly lump species. I had an email exchange about this with the GFED folks in 2014. And I think that what what was done and that is why the emission factors for these lumped species are in fact in  carbon units.

**Comment by pkasibhatla** [comment]
Just to add .. if you look at the excel spreadsheet (https://www.geo.vu.nl/~gwerf/GFED/GFED4/ancill/GFED4_Emission_Factors.xlsx) showing how the lumping is being done for higher alkanes and alkenes, you will see that the listed emission factors are indeed in units of g C/g DM burned.
