### ISSUE TITLE
How to make sure new emissions have been read in the HEMCO?

### ISSUE THREAD

**Issue by jinlx** [geoschem/HEMCO#241]
### Name and Institution (Required)

Name: Lixu Jin
Institution: The University of Montana

### Description of your issue or question
I was trying to include an off-gassing emission for furfural (one of VOCs that haven't been included in the GEOS-Chem yet). Unlike GFED/CEDS, which we could tell if they are read in the GC.log (see below), I am not sure if my newly added emission data is read or not. I was wondering if there is any way to figure it out? The setting of building emissions can be found in the HEMCO_Config by searching BUILDING or LIXU. Please let me know if there is anything else you need to further check. Thanks!

```
HEMCO: Opening /hellgate/home/lj152920/project/geos-chem/ExtData/HEMCO/GFED4/v2020-02/2017/GFED4_gen.025x025.201706.nc
HEMCO: Opening /hellgate/home/lj152920/project/geos-chem/ExtData/HEMCO/CEDS/v2020-08/2017/CO-em-solid-biofuel_CEDS_2017.nc
```

HEMCO version:  3.6.2

Relevant configuration and log files:
[HEMCO_Config.log](https://github.com/geoschem/HEMCO/files/12651543/HEMCO_Config.log)
[GC.log](https://github.com/geoschem/HEMCO/files/12651525/GC.log)

**Comment by yantosca** [comment]
Thanks for writing @jinlx.  You can turn on `Verbose: 3` in the `HEMCO_Config.rc` file.  This will write out a lot of data but you will see if your emissions are being read if you search through the log file.

NOTE: In HEMCO 3.7.1/GEOS-Chem 14.2.1 we have replaced e.g. `Verbose: 3` with `Verbose: true`.  It will have the same effect.

**Comment by jinlx** [comment]
Thank you Bob! This very helpful! After so. I got following related lines in the log output. In my understanding, the building emission is skipped. Is this any way to bypass influence of CEDS_GBDMAPS_FURFUR_bIND and read in the building emissions as well? Thanks! ~Lixu

```
Added the following option:  BUILDING:        true


Register_Base: Checking BUILDING
HEMCO: Entering Get_targetID (HCO_CONFIG_MOD.F90) ( 4)
Skip container BUILDING because of CEDS_GBDMAPS_FURFUR_bIND
HEMCO: Leaving Get_targetID (HCO_CONFIG_MOD.F90) ( 4)
Container ID     :         2004
Assigned targetID:         -999
```

**Comment by yantosca** [comment]
Sorry for the late reply @jinlx.  I think you can try increasing the Hierarchy value, which should cause HEMCO to take the BUILDING emissions over the CEDS emissions.  See:
- https://hemco.readthedocs.io/en/stable/hco-ref-guide/hemco-config.html#base-emissions

**Comment by yantosca** [comment]
Closing out this issue now
