### ISSUE TITLE
The self-built Inventory cannot be read correctly into GC model

### ISSUE THREAD

**Issue by Liyl2** [geoschem/HEMCO#246]
### Name and Institution (Required)

Name: Liyl
Institution: Southern University of Science and Technology，China

Hello, I am using GCClassic v14.0.2 to add and simulate HCFC-132b substances,It can already be simulated normally. 

But when I use population density to allocate the total global annual emissions, the self-built Inventory shows that the emissions do not enter the GC through the HEMCO diagnosis（EmisHCFC132b_Total）, and when replacing HCFC-132b self-built Inventory with  other substances’ EDGAR Inventory, the display can be read, so it should be a problem with my self-built Inventory, but I can't find where the problem is, can you help me? Please refer to the append files，Thank you very much!

[append files.zip](https://github.com/geoschem/HEMCO/files/13175671/append.files.zip)

**Comment by yantosca** [comment]
Thanks for writing @Liyl2.  It looks like your netCDF file does not have the proper attributes to be read in by HEMCO.  For more information, please see:

- [Prepare COARDS-compliant netCDF files](https://hemco.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/coards-guide.html)
- [Work with netCDF files](https://hemco.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/netcdf-guide.html)

**Comment by Liyl2** [comment]
It's been resolved, thank you very much!

**Comment by yantosca** [comment]
Thank you @Liyl2!  I will close out this issue now.
