### ISSUE TITLE
Assistance running HEMCO Standalone online SoilNOx 

### ISSUE THREAD

**Issue by tanksnr** [geoschem/HEMCO#247]
### Name and Institution (Required)

Name: Mogesh Naidoo
Institution: CSIR

### Confirm you have reviewed the following documentation

- [x ] [Support guidelines](https://hemco.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x ] [User manuals](https://hemco.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x ] [Debugging GEOS-Chem and HEMCO errors](https://hemco.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x ] [Current and past Github issues](https://github.com/geoschem/HEMCO/issues)

### Description of your issue or question
Hi everyone, 

I am running HEMCO Standalone 3.7.1. 
I am attempting to run the online SoilNOx extension (104) using input data downloaded from:
http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/SOILNOX/v2014-07/
This includes the land-cover, fertilizer and default deposition reservoir. 
I also include MERRA-2 input. 

The error I'm getting is:
```
HEMCO ERROR: Cannot fill extension field DRY_TOTN
 --> LOCATION: ExtDat_Set_2R (hcox_state_mod.F90)
 
HEMCO ERROR: Cannot fill extension field WET_TOTN
 --> LOCATION: ExtDat_Set_2R (hcox_state_mod.F90)
 
HEMCO ERROR: DRYCOEFF not defined


```
To me this looks like the extension requires dry and wet deposition from a host atmospheric model. 
I do provide input of "DEP_RESERVOIR", and from the log it looks like the field is being filled. 
Does the DEP_RESERVOIR_DEFAULT data not replace the DRY_TOTN and WET_TOTN fields? 
Or do I absolutely need to run GEOS-Chem to make use of the online soilnox extension? 
I'm also not sure where to define DRYCOEFF. 

I'm attaching the config and log files here:

[HEMCO_Config.rc.txt](https://github.com/geoschem/HEMCO/files/13266777/HEMCO_Config.rc.txt)
[HEMCO_current.log](https://github.com/geoschem/HEMCO/files/13266778/HEMCO_current.log)
[HEMCO_Diagn.rc.txt](https://github.com/geoschem/HEMCO/files/13266779/HEMCO_Diagn.rc.txt)
[HEMCO_sa_0.6x0.6-RSA_Grid.rc.txt](https://github.com/geoschem/HEMCO/files/13266780/HEMCO_sa_0.6x0.6-RSA_Grid.rc.txt)
[HEMCO_sa_Config.rc.txt](https://github.com/geoschem/HEMCO/files/13266781/HEMCO_sa_Config.rc.txt)
[HEMCO_sa_Time.rc.txt](https://github.com/geoschem/HEMCO/files/13266782/HEMCO_sa_Time.rc.txt)

**Comment by yantosca** [comment]
Thanks for writing @tanksnr.  Have you tried commenting out the entries for DRY_TOTN and WET_TOTN in HEMCO_Config.rc?  Those fields are for passing deposited nitrogen from the GEOS-Chem model to the extension.  You can also comment out entries for other similar fields.

You can certainly also try to run a a GEOS-Chem simulation.  If you turn off chemistry and transport then it should go faster than with those operations turned on.

**Comment by yantosca** [comment]
Also DRYCOEFF is read in as part of the GEOS-Chem dry deposition module.

**Comment by tanksnr** [comment]
> Thanks for writing @tanksnr. Have you tried commenting out the entries for DRY_TOTN and WET_TOTN in HEMCO_Config.rc? Those fields are for passing deposited nitrogen from the GEOS-Chem model to the extension. You can also comment out entries for other similar fields.
> 
> You can certainly also try to run a a GEOS-Chem simulation. If you turn off chemistry and transport then it should go faster than with those operations turned on.

Thank you for having a look. 
There are no entries for DRY_TOTN or WET_TOTN in my HEMCO_Config.rc file. 
I would have thought the DEP_RESERVOIR variable can be used to replace those?
I'll investigate further in the soilnox extension code but it does look that way from the outset. 

For DRYCOEFF, it looks like I can read them in within HEMCO_Config.rc manually or from a netcdf Olson_1992_Drydep_inputs.nc.
