### ISSUE TITLE
[FEATURE REQUEST] Simplify turning off all emissions including extensions

### ISSUE THREAD

**Issue by msulprizio** [geoschem/HEMCO#249]
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard / GCST

### New HEMCO feature or discussion

The EMISSIONS logical switch in HEMCO_Config.rc currently only turns off base emissions and not the emission extensions. The emission extension data are bracketed by the logical so those data are not read in. However, because the extensions themselves are still technically on, they get called in HEMCO and result in the model crashing because the input data can't be found.

We need a more elegant solution for disabling all emissions. This should involve moving the EMISSIONS logical outside of the base emissions (ExtNr=0) section:

```
# ExtNr ExtName                on/off  Species   Years avail.
0       Base                   : on    *
# ----- MAIN SWITCHES ---------------------------------------------------------
    --> EMISSIONS              :       true
    --> METEOROLOGY            :       true      # 1980-2021
    --> CHEMISTRY_INPUT        :       true

```

It would also be a good idea to better separate the emissions and non-emissions data (chemistry input) - perhaps even splitting them off into a separate HEMCO_Config.rc file as is currently done for the met fields.

This should be considered when doing the general HEMCO_Config.rc overhaul as discussed in https://github.com/geoschem/HEMCO/issues/102.

**Comment by lizziel** [comment]
Related issue: https://github.com/geoschem/geos-chem/issues/1420
