### ISSUE TITLE
[QUESTION] Output frequency setting for HEMCO_Diagnostics does work? Is is possible to set output frequency and location for HEMCO_restart?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/HEMCO#26]
Hello,

I am using GC 12.2.1, I just found that that my `DiagnFreq` defined in `HEMCO_Config.rc` does not work well. I did not change the `DiagnFreq` value, which is `END`, for the downloaded `HEMCO_Config.rc` file. However, the output `HEMCO_diagnostics` files are on a daily basis. I have also  talked with others who use GC 12.5, which seems to output `HEMCO_diagnostics` files on a monthly basis even if the `DiagnFreq` value is set to `END`. I am wondering if this value can be read into GC correctly?

Meanwhile, is it possible to set output location, frequency, and time stamp for `HEMCO_restart` files as `HEMCO_diagnostics` files? It is said [here](http://wiki.seas.harvard.edu/geos-chem/index.php/The_HEMCO_User%27s_Guide#Restart) that default output frequency for `HEMCO_restart` files is `END`. Again however, I have received daily files. For GC 12.5, it seems to be monthly files.

Thanks in advance!

Yours faithfully,
Fei

**Comment by neyranaz** [comment]
Hello, we are running a 4x5 aerosol only,  using  GC 12.7 to obtain Boundary Conditions for a nested grid simulation. When we do our runs, (Which are at least 4 months long) we are just obtaining restart files at the end of the simulation. So we wanted to know how could we get Daily Restart files as Fei-Yao was obtaining, instead of End restart files as Fei Yao wanted. 

Also is there some sort of sintax that we could use to set the restart frequency to Daily instead of End in HISTORY.rc?

**Comment by msulprizio** [comment]
@neyranaz To save out daily restart files, you can change the frequency and duration of the Restart collection in HISTORY.rc from `'End'` to `00000001 000000` (YYYYMMDD hhmmss format). For example:

```
#==============================================================================
# %%%%% THE Restart COLLECTION %%%%%
#
# GEOS-Chem restart file fields
#
# Available for all simulations
#==============================================================================
  Restart.filename:           './GEOSChem.Restart.%y4%m2%d2_%h2%n2z.nc4',
  Restart.format:             'CFIO',
  Restart.frequency:          00000001 000000,
  Restart.duration:           00000001 000000,
  Restart.mode:               'instantaneous'
  Restart.fields:             'SpeciesRst_?ALL?               ', 'GIGCchem',
                              'Chem_H2O2AfterChem             ', 'GIGCchem',
```

See this wiki page for more details: http://wiki.seas.harvard.edu/geos-chem/index.php/Overview_of_History_diagnostics.

**Comment by neyranaz** [comment]
It works! thanks a lot @msulprizio

**Comment by yantosca** [comment]
Thanks @neyranaz.  I'll close out this issue.
