### ISSUE TITLE
Some online MEGAN species cannot be saved to diagnostics in standalone HEMCO 

### ISSUE THREAD

**Issue by lwcugb** [geoschem/HEMCO#271]
### Name and Institution (Required)

Name: Wei Li
Institution: NOAA ARL

### Description of your issue or question
I am running HEMCOv3.8 standalone to save out natural emissions from MEGAN and soil NOx. The issue is I cannot save out MOH, CH2O, and C2H4 to the diagnostics. I have turned them on in the  HEMCO_Diagn.rc file like below. It works for me in an old version v3.6.2.
```console
InvMEGAN_MOH         MOH    108  -1  -1  2   kg/m2/s  Methanol_emission_flux_from_MEGAN_extension
InvMEGAN_CH2O       CH2O    108  -1  -1  2   kg/m2/s  Formaldehyde_emission_flux_from_MEGAN_extension
InvMEGAN_C2H4       C2H4    108  -1  -1  2   kg/m2/s  C2H4_biogenic_emission_flux_from_MEGAN_extension
```
I am using offline soil NOx for now because the online version needs 'DRYCOEFF' parameter to be read from the Olson_Land_Map_201203/Olson_2001_Drydep_Inputs.nc file. I am not sure how I should set it up to read the file in the standalone simulation. Any advice would be greatly appreciated!

Thanks,
Wei

**Comment by yantosca** [comment]
Thanks for writing @lwcugb.  Would you be able to attach your entire `HEMCO_sa_Config.rc`, `HEMCO_Config.rc`, and `HEMCO_Diagn.rc` config files to this issue?  That would help us diagnose the problem.

**Comment by lwcugb** [comment]
Sorry about that. I attached them below. I do not use HEMCO_sa_Config.rc.
[HEMCO_Config.rc.megan.txt](https://github.com/geoschem/HEMCO/files/14889803/HEMCO_Config.rc.megan.txt)
[HEMCO_Diagn.rc.txt](https://github.com/geoschem/HEMCO/files/14889805/HEMCO_Diagn.rc.txt)

**Comment by yantosca** [comment]
Thanks for the config files @lwcugb.  Try the following.

1. CH2O and C2H2 are not listed as MEGAN species.  You'll need to add these in `HEMCO_Config.rc`:
```console
108     MEGAN                  : on    ISOP/ACET/PRPE/C2H4/ALD2/MOH/EOH/MTPA/MTPO/LIMO/SESQ/SOAP/SOAS/C2H2/CH2O
```
2. Add these lines to `HEMCO_Diagn.rc`
```console
EmisCH2O_Biogenic  CH2O   108    -1  -1   2   kg/m2/s  CH2O_emission_flux_from_biogenic_sources
EmisC2H2_Biogenic  CH2O   108    -1  -1   2   kg/m2/s  C2H2_emission_flux_from_biogenic_sources
EmisMOH_Biogenic   MOH    108    -1  -1   2   kg/m2/s  MOH_emission_flux_from_biogenic_sources
```
This should save out the diagnostics properly.  If not, then let me know!

**Comment by lwcugb** [comment]
It does not seem to work. I added CH2O to the species list and the model crashed with an error message:

HEMCO ERROR: Invalid species names: CH2O

I do not know why this happened because I do see CH2O in the hcox_megan_mod.F90 file.

Thanks,
Wei

**Comment by yantosca** [comment]
@lwcugb: You might need to add CH2O to the `HEMCO_sa_Spec.rc` file.  That tells HEMCO that CH2O is a species.  Also you'd need to copy the name and molecular weight from the GEOS-Chem species_database.yml file.

**Comment by lwcugb** [comment]
I added C2H4 and MOH to the HEMCO_sa_Spec.rc file and now they can be saved. CH2O is already in the file. I guess CH2O  may not be a MEGAN emission species in HEMCO. I will not save it.

**Comment by yantosca** [comment]
Thanks for the feedback!  CH2O is definitely an emission species in HEMCO.  You should be able to archive it.

**Comment by lwcugb** [comment]
I am only running biogenic emissions, and I mean CH2O is not emitted from MEGAN. Although there is emission factor of CH2O in the MEGAN extension codes, I did not find its flux array. https://github.com/geoschem/HEMCO/blob/4e818813da35bf76dbcee2da6ecc598b9c89b1a7/src/Extensions/hcox_megan_mod.F90#L198-L229.
