### ISSUE TITLE
[FEATURE REQUEST] Use HCO_Error in HEMCO error handling

### ISSUE THREAD

**Issue by lizziel** [geoschem/HEMCO#29]
Throughout HEMCO the error handling often consists of this:

`IF ( RC /= HCO_SUCCESS ) RETURN`

or this:

```
IF ( some condition ) THEN
   RC = HCO_FAIL
   RETURN
ENDIF
```

The error is ultimately caught at the highest level calling routine and a generic HEMCO error print is sent to the log instructing users to look at HEMCO.log. This approach has a few issues:

1. There is not always a helpful error message in HEMCO.log.
2. If there is a message sent to HEMCO.log prior to the return it is written by the root thread. If running with MPI the error could occur on a different thread and the error message may therefore not be written before the program stops.
3. There is no traceback of where the error occurs.

A better solution is to replace this sort of error handling with use of the existing HEMCO subroutine HCO_Error followed by Return:

```
! !IROUTINE: HCO_Error                                                                    
!                                                                                         
! !DESCRIPTION: Subroutine HCO\_Error prompts an error message and sets RC to              
! HCO\_FAIL. Note that this routine does not stop a run, but it will cause a              
! stop at higher level (when RC gets evaluated).
```

Upon error, a message would be printed prior to returning up the calling stack. Most critically, the message print would not be restricted to the root thread making the error handling more informative for MPI runs.

**Comment by lizziel** [comment]
This has become an increasing problem for GCHP and now for HEMCO in CESM as well. We will try to prioritize addressing as many instances of this as possible in 12.9.

**Comment by jimmielin** [comment]
Adding a tip for debugging in MPI environments: if you set the HEMCO log in `HEMCO_Config.rc` to `*` (instead of `HEMCO.log`) HEMCO will write log data to standard output. This may not have enough verbosity to debug the problem, but it will allow you to pinpoint where exactly the crashing process was, instead of just guessing from the root CPU log.

**Comment by msulprizio** [comment]
Is this now resolved in HEMCO 3.0.0 or is this still a work in progress?

**Comment by lizziel** [comment]
I think this is still a work in progress.

**Comment by lizziel** [comment]
I'm revisiting this feature request after some painful debugging of an error originating from a missing `HEMCO_Config.rc` line in a HEMCO extension entry. When `HCO_MSG` is called in HEMCO only the root CPU prints the message. This is a problem when running an MPI application since in some cases `HCO_ERROR` calls `HCO_MSG`.

Thinking long-term, I think the best solution for ongoing HEMCO error handling issues would be to tap into the [pFlogger](https://github.com/Goddard-Fortran-Ecosystem/pFlogger) library. This is now used in GCHP, though not in the GEOS-Chem repository code just yet. GC-Classic could benefit as well though my priority right now is MPI applications.

@christophkeller, @tclune: Given use of HEMCO in GEOSgcm, do you know if anyone at GMAO is planning on incorporating pFlogger into HEMCO? If we (GCST) did this would it cause you any issues? I believe we talked about this before, but I also want to double-check it would not cause any issues when run as a non-MPI application.

@christophkeller, I am also generally wondering about your thoughts of replacing HEMCO error handling with pFlogger.

**Comment by christophkeller** [comment]
I am generally very supporting of this idea, and the current error handling certainly needs updating. It would be nice if this could be done in a way that HEMCO standalone can still run without too many dependencies.

**Comment by jimmielin** [comment]
I also support improving the error handling, but I was wondering if pFlogger can be compiled without MPI support? One of the reasons (I imagine) for using GEOS-Chem "Classic" is because of the difficulty to set up an MPI environment. Adding an additional dependency that is not used in GC-Classic & HEMCO standalone could be burdensome for users.

MPI applications (like GCHP, WRF-GC & CESM2-GC) would greatly benefit from this though!

**Comment by lizziel** [comment]
I've moved the discussion about pFlogger to https://github.com/geoschem/geos-chem/discussions/871.

**Comment by lizziel** [comment]
For now I am doing a quick fix of changing the calls to HCO_Error without passing the config%err object throughout all of HEMCO. This addresses the following problems:

1. HCO_ERROR was sometimes called to print error messages to HEMCO.log and other times called to print error messages to stdout. This led to confusion about where to look for error messages.
    
2. If the error message was passed to HEMCO.log then it was only written by the root thread. Because HCO_ERROR is called right before early program termination the root thread would sometimes not get to write the message before early exit. This was especially true for MPI applications with many cores.
    
3. Passing the error message to HEMCO.log requires that the HEMCO.log is open. But the HEMCO.log file is only opened by the root thread and other processes can get ahead of that if using many cores.
    
The subroutine that HCO_ERROR invokes if passing messages to HEMCO.log is still present in the code but will be reassessed in the future. For now, writing messages when there is early termination to std out and by all threads is the most straightforward and consistent way to alert users to the source of the error.

I am also adding code to both HEMCO and GEOS-Chem to include the PET number in error messages if using ESMF. This helps isolate the unique error message traceback in potentially a large number of duplicates.

Once these updates are done I will link to the PR here and close this issue.

**Comment by tclune** [comment]
Was on vacation and just catching up.  There are no specific plans to add pFlogger into the HEMCO gridded component per se.     As with other GEOS components the nominal plan is to introduce such functionality as needed.

**Comment by lizziel** [comment]
See https://github.com/geoschem/HEMCO/pull/111 for the updates I describe above.
