### ISSUE TITLE
[FEATURE REQUEST] Update User's Guide for HEMCO 3.0.0 release

### ISSUE THREAD

**Issue by msulprizio** [geoschem/HEMCO#36]
The HEMCO User's Guide currently at http://wiki.seas.harvard.edu/geos-chem/index.php/The_HEMCO_User's_Guide contains a lot of information on a single page and is outdated in many places. The documentation needs to be updated to reflect the updates in this repository. This should be complete by the HEMCO 3.0.0 release, which will be concurrent with the GEOS-Chem 13.0.0 release.

**Comment by msulprizio** [comment]
The HEMCO user's guide has been moved to https://hemco.readthedocs.io/en/latest/. Right now, the basics for getting started are included there. I still plan to add more detailed information there prior to the final 3.0.0 release.

**Comment by jimmielin** [comment]
Hi Melissa,

Thanks so much for working on the documentation. I was looking at the HEMCO documentation at Readthedocs earlier and noticed that it doesn't have a stylesheet like the GCHP documentation. I was wondering if maybe the theme isn't being included? I've tried several browsers and they all display like this:

![image](https://user-images.githubusercontent.com/123603/155830349-98c30fbe-09d2-4f1f-82cf-34a7f3b91509.png)

Best,
Haipeng

**Comment by yantosca** [comment]
We can close out this issue because we now have good stable documentation at https://hemco.readthedocs.io.
