### ISSUE TITLE
[QUESTION] Units for ALK4, C2H6, and C3H8

### ISSUE THREAD

**Issue by Zitely** [geoschem/HEMCO#38]
## Type your question:
In the HEMCO_Diagn.rc I see that ALK4, C2H6, and C3H8 emissions have OutUnit as kg/m2/s. Does this mean that in this newer version of HEMCO standalone they are no longer calculated in kgC?

[HEMCO_Diagn.txt](https://github.com/geoschem/HEMCO/files/4881432/HEMCO_Diagn.txt)
[HEMCO_sa_Spec.txt](https://github.com/geoschem/HEMCO/files/4881433/HEMCO_sa_Spec.txt)

Note: I just downloaded HEMCO standalone from the GitHub and created a run directory following the [wiki ](http://wiki.seas.harvard.edu/geos-chem/index.php/HEMCO_installation_guide) instructions. 

Thanks,
Zitely

**Comment by msulprizio** [comment]
The emissions of those species is still computed in kgC. The HEMCO standalone uses the same HEMCO_Config.rc as GEOS-Chem 12.8.2 (assuming you point to that file in the setup step), and in that file several emission inventories use kgC for those species. The HEMCO_sa_Spec.rc file linked above still defines MWEMIS as 12.00 and MOLRAT > 1.0 for those species. The use of kg/m2/s in HEMCO_Diag.rc just tells HEMCO to save out those species in those units, but you may change it to kgC/m2/s if you prefer to output in those units.

**Comment by Zitely** [comment]
Thanks for your response. 
I actually prefer the results in kg of specie. So, if I understood correctly, I should just leave it as is, right?

**Comment by msulprizio** [comment]
Yes, exactly. Specifying kg/m2/s in HEMCO_Diagn.rc will tell HEMCO to convert to those units for the diagnostic output.

**Comment by Zitely** [comment]
Great! Many thanks

**Comment by drnimbusrain** [comment]
@msulprizio 

Hi Melissa,

Sorry to ask a similar question again here, but in latest HEMCOv3, do the same rules apply?  For example, if I have a HEMCO input emission inventory in kgC/m2/s, but want the output in kg/m2/s, does HEMCO do the conversion by specifying in the HEMCO_Diagn.rc file?

Example for ACET:

HEMCO Config File:
ExtNr Name sourceFile sourceVar sourceTime C/R/E SrcDim **SrcUnit** Species ScalIDs Cat Hier
0 NEI2016v1_NONPT_ACET           $ROOT/NEI2016v1/v2020-07/$MM/NEI2016v1_0.1x0.1_2016$MM$DD_nonpt.nc          ACET          2016/1-12/1-31/$HH C xy  **kgC/m2/s** ACET        1007     5 50

HEMCO Spec File:
ID NAME MW MWEMIS MOLECRATIO K0 CR PKA
31 ACET         58.1  12.0 3.0  0.0 0.0 0.0

HEMCO Diag File:
Name      Spec ExtNr Cat Hier Dim **Unit**
ACET         ACET           -1    -1  -1   2   **kg/m2/s**

Also, does simply specifying the SrcUnit as kg/m2/s in the HEMCO config file have the same effect, i.e.,
0 NEI2016v1_NONPT_ACET           $ROOT/NEI2016v1/v2020-07/$MM/NEI2016v1_0.1x0.1_2016$MM$DD_nonpt.nc          ACET          2016/1-12/1-31/$HH C xy  **kg/m2/s** ACET        1007     5 50

Thank you,

Patrick
