### ISSUE TITLE
[BUG/ISSUE] HEMCO will not compile with gfortran 9.2.1

### ISSUE THREAD

**Issue by yantosca** [geoschem/HEMCO#4]
# Report a HEMCO bug or technical issue

## Describe the bug
See https://github.com/geoschem/geos-chem/issues/113 for a complete description of the issue. This is an issue that only happens with GNU Fortran 9.2.1 and higher.  

## Additional context
Long story short, in hco_config_mod.F90, we have an output variable N that is the same name as the loop index variable N.  Because the loop index variable cannot be changed in a loop, this now throws an error whereas it did not before.

We will fix the code in GEOS-Chem but this will also need to be added to HEMCO.

**Comment by yantosca** [comment]
This has been resolved in commits https://github.com/geoschem/geos-chem/commit/c349b8a1d9a75e10bc837ac316b09814d4a14422.  I think we might stillt have to bring this fix into the geoschem/HEMCO repository.

**Comment by lizziel** [comment]
This update is in the HEMCO repository branch being developed for use with GEOS-Chem 13.0.0. I am therefore closing this issue. If there are future problems with building HEMCO with gfortran 9.2.1 we can create a new issue.
