### ISSUE TITLE
[FEATURE REQUEST] Vertical Allocation Enhancement

### ISSUE THREAD

**Issue by barronh** [geoschem/HEMCO#46]
Intro
=====

The injection height (xyL=1:5) features are great, but it would be great to extend it. Models like EMEP[1,2] and Hemispheric CMAQ[3] use "representative" sector-based profiles based on the literature[4] to allocate to layers. These layer allocations are fractional, but are not uniform. 

There are a couple of ways to do this in HEMCO. I am curious if you recommend one of the existing methods, or something new.

Existing working mechanisms:
====================
1. xyL=l:u with xyz scale factor (works, but delicate)

This approach is a little tricky. The scale factor must be the fraction profile normalized mean, and it must have the same number of layers as used to spread (`l:u`). This works because you are applying a normalized increase compared to the uniform allocation. Using the wrong number of layers (`xyL=l:u+1`) would result in mass loss.

2. xy emissions with repeated xyL=l

The current version could work by repeating all the emission lines using multiple scaling factors and changing the `l`. This would be cumbersome for sure.

Alternative approaches:
===============

1. xy emissions with xyz scalar (tried)

My hope was that the xy emission would be broadcast to and multiplied by each xyz level. Instead, I think the xy was multiplied by the layer 1 fraction. This would be a pretty cool and flexible. In my tests, I was using an older version of HEMCO due to trouble building the standalone version on our system.

2. Scale Factors

Could a scale factor have srcDim z? If so, the xy emissions could be broadcast to each level.

Summary
======

So far, the existing option with xyL=1:N and a scale factor with N layers seems like the best option. Does this seem like the right approach? Or should a new feature be added to make this cleaner?

Thanks,

References
========

[1] Simpson, D., Benedictow, A., Berge, H., Bergström, R., Emberson, L. D., Fagerli, H., Flechard, C. R., Hayman, G. D., Gauss, M., Jonson, J. E., Jenkin, M. E., Nyíri, A., Richter, C., Semeena, V. S., Tsyro, S., Tuovinen, J.-P., Valdebenito, Á., and Wind, P.: The EMEP MSC-W chemical transport model – technical description, Atmos. Chem. Phys., 12, 7825–7865, https://doi.org/10.5194/acp-12-7825-2012, 2012.

[2] Publicly available EMEP input. EmisHeights.txt in ftp://ftp.met.no/projects/emep/OpenSource/202001/input_data/other_input_files.tar.bz2

[3] See section 2.1.4 from U. S. EPA, 2019. Preparation of Emissions Inventories for the Version 7.1 2016 Hemispheric Emissions Modeling Platform. U.S. Environmental Protection Agency, Research Triangle Park, NC. url: https://www.epa.gov/sites/production/files/2019-12/documents/2016fe_hemispheric_tsd.pdf

[4] Bieser, J., Aulinger, A., Matthias, V., Quante, M., Denier van der Gon, H.A.C., 2011. Vertical emission profiles for Europe based on plume rise calculations. Environmental Pollution 159, 2935–2946. https://doi.org/10.1016/j.envpol.2011.04.030

**Comment by msulprizio** [comment]
This feature has now been added to the `dev` branch and will be included in GEOS-Chem 13.1.0 / HEMCO 3.0.0. See commit https://github.com/geoschem/HEMCO/commit/bc18cc865178d4ba144419983ce829b072fb93c5 and the corresponding run directory updates in https://github.com/geoschem/geos-chem/commit/87eb68ee4d6b523664b12f21b25cf34d064d1ccf. 

Essentially, we now copy 2D emissions vertically to all levels using the dimension `xyL*` in HEMCO_Config.rc. A scale factor can then be applied to distribute the emissions vertically. This is currently done using scale factors read from a netCDF file containing ratios by GEOS-Chem level, as provided by Barron Henderson. The original CSV file, the netCDF file, and the script used to generate the netCDF file may be found in [`ExtData/HEMCO/VerticalScaleFactors/v2020-05`](http://geoschemdata.computecanada.ca/ExtData/HEMCO/VerticalScaleFactors/v2020-05/).

**Comment by msulprizio** [comment]
The vertical allocation of ship emissions has been removed after the initial 1-month benchmark (13.1.0-beta.0) indicated decreases in ship NOx emissions (handled by PARANOX). To avoid complications, we have removed the scale factor application for all CEDSship emissions and keep those emissions as 2D. This has been benchmarked and marked with tag 13.1.0-beta.1.

**Comment by barronh** [comment]
Hi all, a couple folks (including me) noticed that vertical allocation is not included on the CEDSv2 updates. Was this intentional?

**Comment by msulprizio** [comment]
> Hi all, a couple folks (including me) noticed that vertical allocation is not included on the CEDSv2 updates. Was this intentional?

This was not intentional. It is a bug and we will fix it in 14.1.0. See https://github.com/geoschem/geos-chem/issues/1646 for the status.
