### ISSUE TITLE
HEMCO Regridding of Unitless Data

### ISSUE THREAD

**Issue by drnimbusrain** [geoschem/HEMCO#48]
## Type your question:

Can HEMCO perform A2A regridding on unitless data?  

I am testing HEMCO IO to read unitless (or other units except emissions type, e.g., K, m/s, none, etc.) data and output the regridded data.  I thought it should preserve the absolute values and simply do the regridding; however, I am getting erroneous output values.  

From the description of the A2A code, it says:  "This routine can remap concentrations and index-based quantities."  

The input files are formatted for HEMCO and 0.1x0.1 degree.   

Example Input of an index-based quantity:
![image](https://user-images.githubusercontent.com/26631222/91066412-b25bc000-e5ff-11ea-9e7b-6da30556d950.png)  
Note that input index-based values are only 1.

Example Output of an index-based quantity:  
![image](https://user-images.githubusercontent.com/26631222/91065284-46c52300-e5fe-11ea-9e62-5643e76b84e5.png)
Note the erroneously large output values and gradient.

Maybe I am doing something wrong, but it seems HEMCO is forcing an area unit conversion here.
Example Area Output:
![image](https://user-images.githubusercontent.com/26631222/91068779-bfc67980-e602-11ea-9f9e-3cc18fc6924a.png)

Thank you,

Patrick

**Comment by msulprizio** [comment]
I think this may have to do with the way your units are specified in HEMCO_Config.rc. HEMCO expects units `'count'` for index data. You can alway set Verbose and Warnings to 3 in HEMCO_Config.rc to get detailed information in HEMCO.log about the unit conversions being applied to your data.

From `hcoio_read_std_mod.F90`:
```
    !-----------------------------------------------------------------
    ! Convert to HEMCO units
    ! HEMCO data are all in kg/m2/s for fluxes and kg/m3 for
    ! concentrations. Unit conversion is performed based on the
    ! unit on the input file and the srcUnit attribute given in the
    ! configuration file. By default, HEMCO will attempt to convert
    ! the units found in the input file to the standard quantities
    ! for mass (kg), area (m2 or m3), and time (s). For instance,
    ! g/cm2/hr will be converted to kg/m2/s. The exceptions to this
    ! rule are:
    ! 1. If srcUnit is set to '1', the input data are expected to
    !    be unitless. If the units string on the input file is none
    !    of the units recognized by HEMCO as unitless, an error is
    !    returned if the unit tolerance setting is set to zero, or
    !    a warning is prompted if unit tolerance is greater than zero.
    ! 2. If srcUnit is set to 'count', no unit conversion is performed
    !    and data will be treated as 'index' data, e.g. regridding will
    !    preserve the absolute values.
```

**Comment by drnimbusrain** [comment]
Thank you @msulprizio for responding to my question.   Indeed I have  set my verbose/warnings to 3.  

I have set all units to "1" in HEMCO config file and diagnostics, which I thought accomplishes the same thing for essentially unitless variables that are not emissions.   In fact when setting units to "1" it seems to treat it as "count", because the log explicitly states:

"Based on srcUnit attribute (count), no unit conversion is performed.
   ==> Use map_a2a regridding"

Also, from the HEMCO users guide:  

**srcUnit attribute**
"The srcUnit attribute in the HEMCO configuration file gives the user some control on unit conversion: **If set to '1', data are treated as unitless irrespective of the units attribute on the file.** This option works on all fields only if unit tolerance is relaxed to 2 (for unit tolerance of 1, the input data must be in one of the units recognized by HEMCO as unitless). If srcUnit is set to 'count', the input data is assumed to represent index-based scalar fields (e.g. land types). **No unit conversion is performed on these data and regridding will preserve the absolute values**."
...
 **Unitless data**
"The following units are currently recognized as 'unitless' by HEMCO: **1**, count, unitless, fraction, factor, scale, hours, v/v, v/v/s, s-1, m2/m2, kg/kg, K, W/m2, pptv, ppt, ppbv, ppb, ppmv, ppm, ms-1, m, cm2cm-2, dobsons, dobsons/day, hPa, Pa."


Just to check, I tested again changing "1" to "count" for the srcUnit in the HEMCO config file, and I still get the same erroneous results for my example below.  
![image](https://user-images.githubusercontent.com/26631222/91094018-345fdf00-e628-11ea-91c1-eeed0fefed60.png)

Also, HEMCO will not allow "count" as the Unit in the diagnostic file as it stops with the error:  
"HEMCO ERROR: Cannot find mass scale factor for unit count
ERROR LOCATION: Diagn_Create (hco_diagn_mod.F90)"

I find that these Unit values in the diagnostic file must remain as "1" to avoid this error in HEMCO.

Any further help is much appreciated.

Thank you,

Patrick

**Comment by drnimbusrain** [comment]
Hi @msulprizio. I think maybe my earlier issues arise from trying to read those datasets in the wrong place in the HEMCO config file.  I moved them to NON-EMISSIONS section, and set the extension number to *.  However, while it reads through, it always assigns an empty array.  I see at the end of the log file:  

HEMCO WARNING: Diagnostics counter is zero - return empty array

Can you shed light on why this is?

Thank you,

Patrick

**Comment by msulprizio** [comment]
Hi @drnimbusrain. Can you attach your HEMCO_Config.rc and HEMCO.log files? You will just need to add .txt as an extension and then drag and drop here. Then I can have a closer look.

**Comment by drnimbusrain** [comment]
@msulprizio   Thank you so much Melissa, for having a look!  

[HEMCO_Config.rc.txt](https://github.com/geoschem/HEMCO/files/5125840/HEMCO_Config.rc.txt)
[HEMCO.log.txt](https://github.com/geoschem/HEMCO/files/5125841/HEMCO.log.txt)

You can see at the top of my HEMCO config file, most likely I incorrectly assigned these inputs as base emissions with "0" (which gives the very large values as HEMCO assumes they are base emissions), and then I tested one section of them as NON-EMISSIONS data below in the config file (which assigns them to zero array values).

Thank you again,  Patrick

**Comment by msulprizio** [comment]
I think part of the issue may be in your HEMCO_Config.rc entry:

```
# ExtNr Name sourceFile	sourceVar sourceTime C/R/E SrcDim SrcUnit Species ScalIDs Cat Hier

* NEI2016v1_PT_EGU_STKTK   $ROOT/NEI2016v1_STACK/v2020-07/GRIDDED_stack_groups_ptegu_12us1_2016fh_16j.ncf  STKTK  - C xyz  1 PT_EGU_STKTK 1007     1  1
```

It looks like for Species, you've assigned it to `PT_EGU_STKTK` which is not a HEMCO species. Instead, you'll want to use "-" in the Species column. 

When fields are assigned as base emissions, HEMCO automatically handles adding the flux to the appropriate species. However, when you add non-emissions data you need to tell HEMCO what to do with that field via a HEMCO extension (or elsewhere in the HEMCO code if appropriate). For example, in the case of the TIMEZONES field, in hco_clock_mod.F90, you'll see code where that field is obtained from HEMCO and added to an array for further use.

```
    ! Look for the time zone pointer
    CALL HCO_GetPtr ( HcoState, 'TIMEZONES', &
                      HcoState%Clock%TIMEZONES%Val, RC, FOUND=FOUND )
```

**Comment by drnimbusrain** [comment]
@msulprizio   Thank you Melissa for clearing this up, as you are correct that I will have to add an extension or HEMCO species name to treat these.  I was doing something very simple, just trying to consolidate/regrid these non-emissions data through HEMCO, and thought it automatically read/assign as it does for any base emissions data set.  I will just re-evaluate what to do here.  You can close this issue, and thanks again!

Patrick

**Comment by msulprizio** [comment]
OK great. Feel free to reopen this issue or open a new one later if you have any other questions.
