### ISSUE TITLE
[QUESTION] Is the 'most likely' time slice the ONLY time slice selection scheme for addressing time slice gaps between sourceTime and sourceFile?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/HEMCO#53]
Hi there,

I recently re-read the [HEMCO User's Guide](http://wiki.seas.harvard.edu/geos-chem/index.php/The_HEMCO_User%27s_Guide). I realize that CRE controls the time slice selection if the simulation date is outside the range provided in attribute source time. I then came to wonder "Is the 'most likely' time slice the ONLY time slice selection scheme for addressing time slice gaps between sourceTime and **sourceFile**?". This is because I have found relevant descriptions in many places like the following:

In sourceTime:
- (paragraph 3) If the provided time attributes do not match a datetime of the input file, the 'most likely' time slice is selected.
- (paragraph 8) data of file_200501.nc is used for simulation dates of January 2005 (or any January of a previous year)

In CRE:
- (R (range)) If it is outside of the range of the netCDF time stamps, the closest available date will be used.
- (I (interpolation)) If the simulation starts on January 2004, the value of 2005 is used for years 2004 and 2005.

Actually, I asked similar questions before on HEMCO repo. I would be much appreciated If you can help:

1) confirm that the 'most likely' time slice is the ONLY time slice selection scheme for addressing time slice gaps between sourceTime and **sourceFile**?
2) check proposed wiki modifications [here](https://github.com/geoschem/HEMCO/issues/14) are reasonable and then I can do corresponding modifications for wiki and close issues.

Yours faihfully,
Fei

**Comment by yantosca** [comment]
This issue has been moved to the HEMCO Github page.  Please see: https://github.com/geoschem/HEMCO/issues/53.

**Comment by FeiYao-Edinburgh** [comment]
Thanks for your kind reminder. I will post HEMCO-related issues here from now on. I kindly wait for your clarification on issue here and [here](https://github.com/geoschem/HEMCO/issues/14). I just want some confirmation, so not in a hurry. Thanks in advance!

**Comment by msulprizio** [comment]
> confirm that the 'most likely' time slice is the ONLY time slice selection scheme for addressing time slice gaps between sourceTime and sourceFile?

That is correct. Ideally the times in sourceTime should match the actual times included in sourceFile. If they do not, HEMCO will use the times available in sourceFile and compare to the current simulation time. If a CRE flag of `C` is used, HEMCO will use the closest year available. If a CRE flag of `R` or `E` is used, HEMCO should crash with an error if the simulation time is outside of the times available in sourceFile.

If you are ever in doubt about how HEMCO handles data selection, we recommend you set both Verbose and Warnings to 3 in HEMCO_Config.rc and run a short simulation. The resulting HEMCO.log file will include information about the available dates and times in the input file, the preferred time that HEMCO would like to use, and the selected time used.

> check proposed wiki modifications here are reasonable and then I can do corresponding modifications for wiki and close issues.

Please feel free to make the modifications to the wiki user guide. As mentioned in https://github.com/geoschem/HEMCO/issues/14, we are migrating this documentation to hemco.readthedocs.io and will review all text and make changes where needed.

**Comment by FeiYao-Edinburgh** [comment]
> If they do not, HEMCO will use the times available in sourceFile and compare to the current simulation time. If a CRE flag of `C` is used, HEMCO will use the closest year available. If a CRE flag of `R` or `E` is used, HEMCO should crash with an error if the simulation time is outside of the times available in sourceFile.

In this sense, you might would like to improve the following descriptions for `R`:

> R (range): Data are only considered as long as the simulation time is within the time range specified in attribute sourceTime. <b>The provided range does not necessarily need to match the time stamps of the input file. If it is outside of the range of the netCDF time stamps, the closest available date will be used.</b> For instance, if a file contains data for years 2003 to 2010 and the provided range is set to 2006-2010/1/1/0 R, the file will only be considered between simulation years 2006-2010. For simulation years 2006 through 2009, the corresponding field on the file is used. For all years beyond 2009, data of year 2010 is used. 

- If it is outside the range of the netCDF time stamps, HEMCO should crash. Associated examples expect improvement, too.

I am aware of your release of GEOS-Chem v13.0.0. I am fascinated about the separation of geos-chem, HEMCO, GCClassic, and GCHP, which makes more sense!

**Comment by msulprizio** [comment]
We will improve the description for these time cycle flags in the updated documentation. Thanks for bringing this to our attention.
