### ISSUE TITLE
[QUESTION] What does POGSCAL (scaleID=74) mean?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/HEMCO#54]
Hi there,

I am using GC12.9.3 for merra2_2x25_tropchem simulation.
I found in APEI that 74\*76=POGSCAL\*SV2POG1
```
0 APEI_OCPO $ROOT/APEI/v2016-11/APEI.0.1x0.1.nc OC  1989-2014/1/1/0 C xy kg/m2/s OCPO 73/1002        1 30
0 APEI_POG1 -                                       -    -          - -  -       POG1 74/76/1002     1 30
```
While I found in CEDS that 73\*74\*76=OC2OCPO\*POGSCAL\*SV2POG1
```
0 CEDS_OCPI_AGR   $ROOT/CEDS/v2018-08/$YYYY/OC-em-anthro_CMIP_CEDS_$YYYY.nc            OC_agr            1750-2014/1-12/1/0 C xy kg/m2/s OCPI  72        1 5
0 CEDS_OCPO_AGR   -                                                                    -                 -                  - -  -       OCPO  73        1 5
0 CEDS_POG1_AGR   -                                                                    -                 -                  - -  -       POG1  73/74/76  1 5
```
Hence I am confused with the meaning of POGSCAL. Is it based on OC (APEI) or OCPO (CEDS)? Or is it just due to the difference of APEI and CEDS original data?

**Comment by msulprizio** [comment]
The meaning of POGSCAL is described in [Pye et al. (2010)](https://acp.copernicus.org/articles/10/11261/2010/acp-10-11261-2010.pdf). See also [this description and figure](http://wiki.seas.harvard.edu/geos-chem/index.php/Secondary_organic_aerosols#SOA_simulation_with_semi-volatile_POA) on the wiki. In that description, Havala Pye wrote:

>The code also allows for the option to replace OCPI and OCPO with a semivolatile aerosol that can age in the gas-phase to form lower volatility products.

I believe that means POGSCAL is meant to be applied to total OC. In 13.0.0, we are updating the [CEDS inventory to McDuffie et al. (2020)](https://github.com/geoschem/geos-chem/issues/447) and in that version of HEMCO_Config.rc, the 73 (OC2OCPO) scale factor has been removed from POG entries.

**Comment by FeiYao-Edinburgh** [comment]
Hi @msulprizio ,

Thanks for your clarification on POGSCAL.

I am interested in using the updated CEDS in GC v.12.9.3. I think this is now possible because I have seen you already added a sub-directory, v2020-08, under the current CEDS directory. All I need to do is to update my HEMCO_Config.rc to use these updated instead of original CEDS inventory. However, under the [link](https://github.com/geoschem/geos-chem/issues/447) you provided above, I note that the way listing the CEDS entries does matter the simulation speed. I am not an expert of this and hence wonder do you have a template HEMCO_Config.rc file that works with v2020-08 that I can copy to my GC v12.9.3? Many thanks in advance!

**Comment by FeiYao-Edinburgh** [comment]
Later on I realize that I can always check the associated HEMCO_Config.rc template files via the [dev/13.0.0](https://github.com/geoschem/geos-chem/tree/dev/13.0.0/run) branch of your geos-chem repo. Conveniently I can also see all and recent updates you have made through commits. Please feel free to close this issue.
