### ISSUE TITLE
Question about dev/GC_13.0.0 Branch

### ISSUE THREAD

**Issue by drnimbusrain** [geoschem/HEMCO#65]
Hi @msulprizio et al.,

I have a question about the previous "dev/GC_13.0.0" branch, which has since been deleted it seems.  Do you now recommend we use the "main" branch for HEMCO standalone tests and development here at NOAA-ARL?

Thank you very much,

Patrick

**Comment by msulprizio** [comment]
Hi @drnimbusrain. Yes, please use the main branch for HEMCO standalone tests and development from now on. We will be officially releasing this version (HEMCO 3.0.0) in early January (after we return from Harvard's winter break), but it is ready to use now. I've setup a [video tutorial on our Youtube channel](https://www.youtube.com/watch?v=6Bup9V0ts6U) walking through a simple HEMCO standalone simulation. I'm also in the progress of updating the HEMCO user's guide which will be officially available at hemco.readthedocs.io when we make the release announcement in January.

**Comment by drnimbusrain** [comment]
Oh wow Melissa, this is excellent information!  Thank you so much, and please have a safe and happy holidays and new year!
