### ISSUE TITLE
[QUESTION] question about running hemco standalone

### ISSUE THREAD

**Issue by grjeong** [geoschem/HEMCO#66]
Dear GEOS-CHEM support team,

I have a few questions about running HEMCO standalone.
I tried to run it according to the tutorial footage of 'getting started with the HEMCO standalone'. But I realized that my HEMCO_config.rc was very different from yours.

         (base) [gjeong@hopper2 run]$ ./createRunDir.sh

         ===========================================================
         HEMCO STANDALONE RUN DIRECTORY CREATION
        ===========================================================

         Warning: Default root data directory does not exist!

         Set new path below or manually edit /home/gjeong/.geoschem/config.

It resulted in HEMCO_sa_Config.rc

          #-----------------------------------------------------
          # Setting for HEMCO standalone input and output
          #-----------------------------------------------------

          #ROOT:               /scratch/gjeong/config/HEMCO

          ROOT:               /scratch/gjeong/HEMCO/run

It also resulted in HEMCO_Config.rc which is almost the same as HEMCO_sa_Config.rc

         #BOC

        ########################################################################

        ### BEGIN SECTION SETTINGS

        ########################################################################

        #-----------------------------------------------------
        # Setting for HEMCO standalone input and output
        #-----------------------------------------------------

        ROOT:                /scratch/gjeong/HEMCO

Finally, I failed to run the HEMCO standalone.

        (base) [gjeong@hopper2 hemco_4x5_merra2]$ ./hemco_standalone > HEMCO_SA.log &

        [1] 155404

        (base) [gjeong@hopper2 hemco_4x5_merra2]$ tail --follow HEMCO_SA.log

  

         Reading entire HEMCO configuration file: HEMCO_Config.rc

         Error reading HEMCO_Config.rc

         HEMCO ERROR: Error encountered in routine "Config_Readfile!"

        ERROR LOCATION: HCOI_SA_Init (in module HEMCO/Interfaces/hcoi_standalone_mod.F90)

 

        HEMCO ERROR: Error encountered in routine "HCO_Sa_Init"!

        ERROR LOCATION:  -> at HCOI_StandAlone_Run (in module HEMCO/Interfaces/hcoi_standalone_mod.F90)

 

         HEMCO_STANDALONE EXITED WITH ERROR!

         ^C[1]+  Done                    ./hemco_standalone > HEMCO_SA.log

I would like to know what kind of emission files you used and whether I would be able to use them for testing HEMCO standalone.

Sincerely,
Gill-Ran

**Comment by yantosca** [comment]
Thanks @grjeong and Happy New Year.

We are about to release HEMCO 3.0.0 (probably later this week), which has a new workflow for the HEMCO standalone.  GCST member @msulprizio has created a tutorial video ([click here to watch](https://www.youtube.com/watch?v=6Bup9V0ts6U&t=25s) that shows you how to download and configure the HEMCO standalone.
