### ISSUE TITLE
[FEATURE REQUEST] Give HEMCO the capability to read/write data as REAL*8

### ISSUE THREAD

**Issue by yantosca** [geoschem/HEMCO#69]
This is related to issue https://github.com/geoschem/geos-chem/issues/111.

Long story short: It is desirable to extend the HEMCO's internal data structures so that they can carry either REAL\*4 or REAL\*8 data arrays.  Currently, HEMCO's data structures allow REAL\*8 data to be read in from disk, but not to be written out to disk.   HEMCO can only write REAL\*4 data to disk.

Recent work by the GEOS-Chem Support Team has shown that writing restart file output as REAL\*8 removes the small numerical differences seen when comparing GEOS-Chem "Classic" simulations that are run as a single stage (e.g. yearly) as opposed to simulations that are broken up into smaller stages (e.g. monthly) and are reinitialized from the previous stage's end-of-run restart file.

**Comment by yantosca** [comment]
I just realized this is a duplicate of #18.  I'll close this one now.

**Comment by liuyuyu223** [comment]
May i ask whether there are difference if i only want to HEMCO the capability to read/write data as REAL*8? I ask because i found the code in 
https://github.com/geoschem/geos-chem/commit/652bb239abed2b12e4331ca0de18d0a3db2de7f7 are mainly for version 13, while i am using version 12.5?
