### ISSUE TITLE
[QUESTION] Can we custom/update emission factors in BB emission inventories?

### ISSUE THREAD

**Issue by jinlx** [geoschem/HEMCO#7]
Hi there,

## Type your question:
I want to update emission factors for some trace gases in biomass burning emission inventories to see if it could improve the performance of the simulation. 

From the information in wiki website, I found that EFs could be modified in HEMCO/Extensions/hcox_gfed_include_gfed4.H. But I can't find how to modify EFs in other inventories. I wonder if you could give me some suggestions on it?

Cheers,
Lixu

**Comment by yantosca** [comment]
Thanks for writing.  

For Base Emissions, you can define scale factors in the HEMCO_Config.rc file as shown in [The HEMCO User's Guide: Scale Factors](http://wiki.geos-chem.org/The_HEMCO_User%27s_Guide#Scale_factors) section.

For extensions, you should be able to scale any species defined in the extension by typing something like this in the Extension options:
```
--> Scaling_CO: 1.20
```

See [The HEMCO User's Guide: Built-in tools for scaling and masking](http://wiki.geos-chem.org/The_HEMCO_User%27s_Guide#Built-in_tools_for_scaling.2Fmasking)

**Comment by jinlx** [comment]
Thanks for getting back to me.

Sorry for the stupid question. If I understand it right, we can modify emission factors of HCHO (for example) in FINN and GFED4 by add something like this. 
```
    --> Scaling_HCHO             :       1.24 or     --> Scaling_CH2O      :1.24
```
Where can we find the specific name for the species (Scaling_XXX)? For QFED and GFAS, there is no place to set scaling_species. So, I still don't know how to modify emission factors in these two. Can you give me more details about that?

Cheers,
Lixu

**Comment by yantosca** [comment]
So for QFED and GFAS, those are base emissions.  You would have to define scale factors for those as defined in [The HEMCO User's Guide](http://wiki.seas.harvard.edu/geos-chem/index.php/The_HEMCO_User%27s_Guide#Scale_factors)

As an example, you can look at:

```
#==============================================================================
# --- QFED2 biomass burning (v2.5r1) ---
#==============================================================================
(((QFED2
0 QFED_ACET_PBL  $ROOT/QFED/v2018-07/$YYYY/$MM/qfed2.emis_acet.006.$YYYY$MM$DD.nc4 biomass 2000-2017/1-12/1-31/0 C xyL=1:PBL     kg/m2/s ACET 75/311        5 2
0
... etc....
```
In this line, the 75 and 311 are the scale factors.  They are defined below here:

```
###############################################################################
### BEGIN SECTION SCALE FACTORS
###############################################################################

#==============================================================================
# --- QFED2 diurnal scale factors ---
#
# Fire diurnal scaling factors (% per hour) from WRAP Report to Project
# No. 178-6, July 2005
#==============================================================================
75 QFED2_TOD 0.1392/0.1392/0.1368/0.1368/0.1368/0.1368/0.1368/0.1368/0.1368/0.48/0.96/1.68/2.4/3.12/3.84/4.08/2.88/1.68/0.96/0.1368/0.1368/0.1368/0.1368/0.1368 - - - xy unitless 1

...etc ...

#==============================================================================
# --- QFED vertical partitioning ---
# Following Fischer et al. (2014) and Travis et al. (2016), emit 35% of QFED
# emissions above the PBL.
#==============================================================================
311 QFED_PBL_FRAC 0.65 - - - xy 1 1
312 QFED_FT_FRAC  0.35 - - - xy 1 1
```

So you could define a new scale factor (it can be either a single number, an array of numbers, or a 2-D array read from a netCDF file) in the scale factor section, following the examples above.  Then you can add the number of the scale factor to the emissions entry for the given species (i.e. 75/311/NN), where NN would be the number of the scale factor that you define.
