### ISSUE TITLE
[QUESTION] Questions about hcox_seaflux_mod.F90 in HEMCO Extension  

### ISSUE THREAD

**Issue by syao2021** [geoschem/HEMCO#72]
In THIS module, it was pointed out that seaflux was calculated using "two-layer" model, F = Kg(Cair - HCwater), and aimed to calculate the source and sink terms separately. 
Source = Kg*H*SeaConc [kg/m2s]
Sinks = Kg/Deposition Height [s-1]

My question is why sinks is calculated according to deposition height and the unit is per second, which is not flux unit. How does it calculate the seaflux. From my perspective, the sink term should be Sink = Kg*Cair, and then seaflux = sink - source. Could u please explain it to me? Many thanks!

**Comment by yantosca** [comment]
Thanks for writing @syao2021.  This is more of a science question, so I would defer to the Aerosol Working Group.

**Comment by yantosca** [comment]
Oops my bad @syao2021, you should check with the Emisisons & Deposition Working Group.

**Comment by syao2021** [comment]
Dear geoschem support team,


I have a question about the seaflux module of HEMCO Extention (hcox_seaflux_mod.F90). In THIS module, it was pointed out that seaflux was calculated using "two-layer" model, which is F = Kg(Cair - HCwater), and aimed to calculate the source and sink terms separately.

Source = Kg&nbsp;* H *&nbsp;SeaConc [kg/m2s]
Sinks = Kg / Deposition Height [s-1]

My question is why sink term is calculated according to deposition height and the unit is per second, which is not flux unit. How does it represent the seaflux? From my perspective, the sink term should be Sink = Kg*Cair, and then seaflux = sink - source. Could u please explain it to me? Many thanks!
I am looking forward to your reply.


Yours sincerely,
Shun&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by syao2021** [comment]
Hi Shun – the sink term as you wrote it is the loss frequency.  It would be multiplied by concentration to get a deposition loss rate.  Daniel

From: 姚舜(YAO Shun) <yaos@mail.sustech.edu.cn>
Sent: Tuesday, February 23, 2021 8:17 PM
To: geoschem/HEMCO <reply@reply.github.com>; geos-chem-emissions <geos-chem-emissions@g.harvard.edu>
Subject: [geos-chem-emissions] Re: [geoschem/HEMCO] Questions about hcox_seaflux_mod.F90 in HEMCO Extension (#72)

Dear geoschem support team,

I have a question about the seaflux module of HEMCO Extention (hcox_seaflux_mod.F90). In THIS module, it was pointed out that seaflux was calculated using "two-layer" model, which is F = Kg(Cair - HCwater), and aimed to calculate the source and sink terms separately.

Source = Kg * H * SeaConc [kg/m2s]
Sinks = Kg / Deposition Height [s-1]

My question is why sink term is calculated according to deposition height and the unit is per second, which is not flux unit. How does it represent the seaflux? From my perspective, the sink term should be Sink = Kg*Cair, and then seaflux = sink - source. Could u please explain it to me? Many thanks!
I am looking forward to your reply.

Yours sincerely,
Shun
------------------ Original ------------------

**Comment by yantosca** [comment]
I will close this issue as it has been answered.

**Comment by jimmielin** [comment]
Hi all,

I was asked for further clarification of this question. I'm adding some notes here for future reference. HEMCO handles source terms (emissions) and sink terms (deposition) differently. This may not be immediately obvious.

The source terms are fluxes (kg/m2/s) and are passed from extensions to HEMCO using
```fortran
call HCO_EmisAdd(HcoState, Source, HcoID, RC)
```

**But loss terms are deposition velocities (1/s)**. The units are different here. This is not a flux, and is handled separately by HEMCO:
```fortran
call HCO_DepvAdd(HcoState, SINK, HcoID, RC)
```

This will **not** affect the existing fluxes. Instead, it adds them to a separate depv term: (see `hco_fluxarr_mod.F90`)
```fortran
    ! Add array
    HcoState%Spc(HcoID)%Depv%Val(I,J) = &
       HcoState%Spc(HcoID)%Depv%Val(I,J) + iVal
```

Thus, **deposition terms also need to be handled by the model separately**. If you are a GEOS-Chem user you don't have to care about this. But if implementing HEMCO in other models, then this code is of interest (in `hco_utilities_gc_mod.F90`):

```fortran
          !------------------------------------------------------------------
          ! Also add drydep frequencies calculated by HEMCO (e.g. from the
          ! air-sea exchange module) to DFLX.  These values are stored
          ! in 1/s.  They are added in the same manner as the drydep freq values
          ! from drydep_mod.F90.  DFLX will be converted to kg/m2/s later.
          ! (ckeller, 04/01/2014)
          !------------------------------------------------------------------
          CALL GetHcoValDep( NA, I, J, L, found, dep )
          IF ( found ) THEN
             dflx(I,J,NA) = dflx(I,J,NA)                                     &
                          + ( dep * spc(I,J,NA) / (AIRMW / ThisSpc%MW_g)  )
          ENDIF
```

Thus the deposition velocity term is actually applied to the state **only at this point**. The formula is as Daniel has pointed out:

```
deposition_flux = depvel * species_mixing_ratio * species_MWg / air_MWg
```

Hope this clarifies the question.
