### ISSUE TITLE
[QUESTION] Does HEMCO add inventories of the same cat and hier for the same species?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/HEMCO#8]
Hi there,

This might be a stupid question but I just would like to confirm. I have read [HEMCO paper] https://www.geosci-model-dev.net/7/1409/2014/gmd-7-1409-2014.html). In Section 2.1, it introduces how HEMCO calculate emission for a certain species from a series of inventories. It indicates that "Within the same category, inventories of higher priority overwrite lower-priority
data, while emissions of different categories are added.", but it does not tell the circumstance for "the same category and the same hierarchy", which is the case I see too much frequently in "HEMCO_Config.rc" like the following.
```
 635 (((MIX
 636 0 MIX_NO_IND   $ROOT/MIX/v2015-03/MIX_Asia_NO.generic.025x025.nc   NO_INDUSTRY      2008-2010/1-12/1/0 C xy kg/m2/s  NO   1/27/25/1006      1 45
 637 0 MIX_NO_POW   $ROOT/MIX/v2015-03/MIX_Asia_NO.generic.025x025.nc   NO_POWER         2008-2010/1-12/1/0 C xy kg/m2/s  NO   1/27/25/1006      1 45
 638 0 MIX_NO_RES   $ROOT/MIX/v2015-03/MIX_Asia_NO.generic.025x025.nc   NO_RESIDENTIAL   2008-2010/1-12/1/0 C xy kg/m2/s  NO   1/27/25/1006      1 45
 639 0 MIX_NO_TRA   $ROOT/MIX/v2015-03/MIX_Asia_NO.generic.025x025.nc   NO_TRANSPORT     2008-2010/1-12/1/0 C xy kg/m2/s  NO   1/27/25/1006      1 45
```
I believe these inventories will be added to each other contributing to CO species, but since there is no statement of this either in paper or in user guide, I would appreciate your confirmation.

Yours faithfully,
Fei

**Comment by yantosca** [comment]
In the example above, the MIX_NO_* are not different inventories, but are different sectors of anthropogenic.  Therefore they get put into category 1.

**Comment by FeiYao-Edinburgh** [comment]
> Therefore they get put into category 1.

So they will all be added to species CO?

How about the case in the following.
```
 799 0 DICE_CHARCOALPROD_CO    $ROOT/DICE_Africa/v2016-10/DICE-Africa-charcoal-production-2013-v01-4Oct2016.nc  CO    2013/1/1/0 C xy g/m2/yr  CO    26/1008/320      1 60
 820 0 DICE_GASFLARE_CO    $ROOT/DICE_Africa/v2016-10/DICE-Africa-gas-flares-2013-v01-4Oct2016.nc  CO    2013/1/1/0 C xy g/m2/yr  CO    26/1008          1 60
 838 0 DICE_AGBURNING_CO    $ROOT/DICE_Africa/v2016-10/DICE-Africa-household-crop-residue-use-2013-v01-4Oct2016.nc  CO    2013/1/1/0 C xy g/m2/yr  CO    26/1008          2 60
```
These three are all selected from `DICE_Africa`, I suppose they three will also be added to CO species?

To sum, I think I only need to worry cat and hier. You have told me how HEMCO process for: same cat with different hier, and different cat. I wonder how HEMCO process: same cat with same hier? Sum or pick a random one?

**Comment by yantosca** [comment]
In the first example, they all of the MIX_NO* get added to NO .

```
636 0 MIX_NO_IND   $ROOT/MIX/v2015-03/MIX_Asia_NO.generic.025x025.nc   NO_INDUSTRY      2008-2010/1-12/1/0 C xy kg/m2/s  NO   1/27/25/1006      1 45
etc
```

The "NO" following the unit string (kg/m2/s) indicates the species into which the data will be added.  So in this case all of the sectors get added into NO.

In your second example, 

```
799 0 DICE_CHARCOALPROD_CO    $ROOT/DICE_Africa/v2016-10/DICE-Africa-charcoal-production-2013-v01-4Oct2016.nc  CO    2013/1/1/0 C xy g/m2/yr  CO    26/1008/320      1 60
etc
```

The CO following the file name indicates the variable of the netCDF file to read.
The CO after the unit string (g/m2/2) indicates that the emissions should go into the CO species.

**Comment by yantosca** [comment]
Same cat, different hier:  HEMCO picks the higher hierarchy number.

Same cat, same hier: HEMCO adds the data together.

Some of this is discussed in this presentation (see pages 19-36): http://acmg.seas.harvard.edu/presentations/IGC8/talks/MonC_Clinics_yantosca_bob.pdf

**Comment by FeiYao-Edinburgh** [comment]
> Same cat, different hier: HEMCO picks the higher hierarchy number.
> Same cat, same hier: HEMCO adds the data together.


Thanks for your confirmation! And also the following.
> Different cat: HEMCO adds the data together.

The second and the third rule will lead to similar species for GC running but the third rule will enable us to do some interesting HEMCO diagnostics!
