### ISSUE TITLE
[BUG/ISSUE] NetCDF DO_ERR_OUT error when reading Yuan XLAI (interpolated data)

### ISSUE THREAD

**Issue by klconferUW** [geoschem/HEMCO#84]
Hi, I encountered a netcdf error halfway through a year long simulation with v13.0.2. I am running a standard 4x5 tropchem.

### Description of modifications
- Special offline sea salt aerosol emissions
- ND51 turned on
- SpeciesConcSubset added for two species in HISTORY.rc
- Compiled with bpch flag on

### Log files

- [GC_std.log](https://github.com/geoschem/geos-chem/files/6378898/GC_std.log)
- [HISTORY3.txt](https://github.com/geoschem/geos-chem/files/6378920/HISTORY3.txt)
- [input_geos.txt](https://github.com/geoschem/geos-chem/files/6378923/input_geos.txt)

<img width="732" alt="Screen Shot 2021-04-26 at 10 18 31 AM" src="https://user-images.githubusercontent.com/82126321/116124137-c1a47900-a678-11eb-8843-e50422f409cf.png">

I ran 2 other simulations with slightly different modifications and all three failed on the same day after creating the same amount of output files. I believe the issue is with the Yuan_XLAI files being read. Does the "quick fix" on the [wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/Leaf_area_indices_in_GEOS-Chem#Quick_fix_to_use_Yuan-processed_MODIS_LAI_in_GEOS-Chem_Classic) apply with v13? 

Thank you!

**Comment by yantosca** [comment]
I have pushed this fix as commit d224b1e285adf616cd55957aa3acf6ae514df3c3  in the geoschem/HEMCO repository.  For now this is on the `bugfix/bmy/interp` branch.  You can apply it with

```console
$ cd GCClassic/src/HEMCO    # Navigate to the HEMCO folder of your GCClassic wrapper, whatever that is named
$ git fetch
$ git pull bugfix/bmy/HEMCO
$ git checkout bugfix/bmy/HEMCO
```

**Comment by klconferUW** [comment]
Hi Bob, thank you for your help! 

For some reason "git pull bugfix/bmy/HEMCO" did not work for me but I have manually adjusted the code from above. Just to confirm it should be:

 INTEGER :: I, nTime

not  INTEGER :: nTime

**Comment by yantosca** [comment]
Thanks @klconferUW.  I meant to add an `INTEGER :: nTime`.  The way I had it is:
```
INTEGER :: I
INTEGER :: nTime
```
but you can put them on the same row.

**Comment by klconferUW** [comment]
Great, thank you so much!

**Comment by yantosca** [comment]
oops, it should have been `git pull origin bugfix/bmy/HEMCO`.   My bad.

**Comment by yantosca** [comment]
I will close this issue -- we now have Pull Request #85 that is pending.
