### ISSUE TITLE
[QUESTION] Much lower GCC offline dust emission outputs than original emission input (regridding method used in HEMCO?)

### ISSUE THREAD

**Issue by 1Dandan** [geoschem/HEMCO#86]
# Ask a question about HEMCO
I am running a GCC v13.0.1 2x2.5 simulation with 0.25x0.3125 offline dust emission inventory. 
I output the HEMCO_diagnostics to get the Dust emission and calculate the total dust (EmisDST1_Total + EmisDST2_Natural + EmisDST3_Natural + EmisDST4_Natural) for 2019 Jan. monthly mean. 
To compare it with original offline dust, I also plot the map for total dust emission (multiplied by the same scaling factor), and the map for GCHP C48 (v13.0.0, same offline dust emission inventory and scaling factor as GCC) total dust emission (Emission collection in HISTORY.rc).
As showed in the figure below, the GCHP C48 dust emission is comparable with original dust emission (Meng20) but GCC 2x2.5 is orders of magnitude lower.
I am suspecting it is related to the regridding method. GCHP is using conservative regridding method, but what regridding method used for GCC HEMCO?
The relevant configuration files are attached ([configuration files.zip](https://github.com/geoschem/HEMCO/files/6664242/configuration.files.zip))
![image](https://user-images.githubusercontent.com/75513026/122251442-1ea9f780-ce90-11eb-8ece-3905746fe97a.png)

**Comment by msulprizio** [comment]
Thanks for writing. HEMCO uses the [MAP A2A regridding method](http://wiki.seas.harvard.edu/geos-chem/index.php/Regridding_in_GEOS-Chem#The_MAP_A2A_algorithm). 

We did do an evaluation of the offline dust emissions in GEOS-Chem 13.0.0 (GCClassic 4x5 vs GCHP c48). The results of that 1-month benchmark (July 2019 w/ MERRA-2) can be found here: http://ftp.as.harvard.edu/gcgrid/geos-chem/1mo_benchmarks/GC_13/13.0.0-offlineEmis/GCHP/BenchmarkResults/GCHP_GCC_comparison/. In particular, see the [emissions totals](http://ftp.as.harvard.edu/gcgrid/geos-chem/1mo_benchmarks/GC_13/13.0.0-offlineEmis/GCHP/BenchmarkResults/GCHP_GCC_comparison/Tables/Emission_totals.txt) for the dust species:

```
###################################################################################
### Emissions totals for species DST1 [Tg]                                      ###
### Ref = GCC_13.0.0-offlineEmis; Dev = GCHP_13.0.0-offlineEmis                 ###
###################################################################################
                                    Ref                 Dev     Dev - Ref    % diff
DST1 Natural       :          12.012706           13.263981      1.251275    10.416
DST2 Natural       :          30.172900           33.315795      3.142895    10.416
DST3 Natural       :          54.747215           60.449787      5.702572    10.416
DST4 Natural       :          59.891026           66.129426      6.238400    10.416
```

It may be that we need to reevaluate the scale factors applied to the offline dust emissions. We are planning on updating the offline dust emissions in 13.2.0 to use files saved out using the Meng et al. (2020) scheme. The updated files should already include the appropriate scaling, so we can remove the scaling applied in HEMCO_Config.rc. Those files were generated by @YanshunLi-washu who may be able to elaborate.

**Comment by 1Dandan** [comment]
Thanks for sharing the benchmark comparison with offline dust emission.

**Comment by YanshunLi-washu** [comment]
@msulprizio Thanks Melissa. @1Dandan Hi Dandan, the newest offline dust emission is available here http://geoschemdata.computecanada.ca/Transfers/OFFLINE_DUST/v2020-05/0.5x0.625/.

But recently the compute canada cluster is experiencing a slowness issue. In case this happen, I am also happy to assist you through our washu compute1 cluster. I will start a email conversation with you. Hope this can help.

Thanks.

**Comment by 1Dandan** [comment]
I have reran the GCC simulation with the same version of 13.0.0. It showed the dust emission is similar now. Not sure what's wrong with previous GCCv13.0.1 settings but it is solved now.
![GCCv130 0 0_GeosFP_2x25_Emission_Dust_201901_MonMean](https://user-images.githubusercontent.com/75513026/127021014-4762c890-cdfc-4bdc-b5e8-69990c63cacc.png)
