### ISSUE TITLE
[QUESTION] How to modify agricultural soils in SoilNOx and agricultural waste burning in GFED4?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/HEMCO#88]
Hi GCST,

Recently we are trying to implement [EDGARv5](https://edgar.jrc.ec.europa.eu/dataset_ap50) into GEOS-Chem. During configuration, we find that the `Agricultural soils` and `Agricultural waster burning` are already included in `SoilNOx` and `GFED4`, which also include natural soils and other open fires, respectively. To avoid double-counting, we'd like to remove `Agricultural soils` from SoilNOx and `Agricultural waste burning` from GFED4. After a check with existing HEMCO_Config.rc, we propose the following solutions that appreciate your confirmation.

For `Agricultural soils`, could we simply remove fertilizer NOx from SoilNOx? If so, the following two solutions should work similarly?

- Solution 1: turn off `Use fertilizer NOx` in `Extension switches`.
  - `--> Use fertilizer NOx     :       false`
- Solution 2: zero out fertilizer NOx.
  - Create a scale factor and assign value 0.0 to it: `400 ZERO 0 - - - xy 1 1`
  - Apply this scale factor to fertilizer NOx: `104 SOILNOX_FERT          $ROOT/SOILNOX/v2014-07/soilNOx.fert_res.generic.05x05.nc      FERT          2000/1-12/1-31/0  C  xy kg/m3 NO 400 1 1`

By solution 2, we can also test the impact of reducing agricultural soil emissions by say 50\% by changing the scale factor value?

For `Agricultural waste burning`, could we simply remove GFED_AGRI from GFED4? If so, the above defined scale factor can be applied again? And we can similarly test the impact of reducing agricultural wast burning by say 50\% by changing the scale factor value?

`111 GFED_AGRI       $ROOT/GFED4/v2020-02/$YYYY/GFED4_gen.025x025.$YYYY$MM.nc  DM_AGRI       1997-2019/1-12/01/0    RF xy kgDM/m2/s * 400 1 1`

Since SoilNOx and GFED4 are extensions, I am not sure whether the above methods can work properly like they do for base emissions? I am kindly wait for your reply. If the answer is no, could you also please guide me to the right way? Many thanks in advance!

All the best,
Fei

**Comment by christophkeller** [comment]
Hi Fei,
all of your proposed solutions will work, as far as I can tell. Which one to use is probably a matter of personal preference. Applying a scale factor of 0 to `GFED_AGRI` and `SOILNOX_FERT` wastes compute time but gives the option to play around with that scale factor, as you point out.
Regarding the fertilizer NOx emissions, note that currently, the `SOILNOX_FERT` values read from file are adjusted within the SoilNOx module to account for variations in fertilizer emissions depending on soil temperature and moisture. You wouldn't have this interaction anymore when getting soil NOx emissions from EDGARv5. Presumably, this isn't a big issue as the agricultural soil emissions in EDGARv5 already reflect the seasonal cycle of fertilizer NOx emissions.

**Comment by FeiYao-Edinburgh** [comment]
Hi @christophkeller Thanks for your reply! I close this issue myself.
