### ISSUE TITLE
[QUESTION] Is setting Cat up to 3 values really useful since emissions will only go into the first one?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/HEMCO#9]
Hi there,

I came across this description "Up to three emission categories can be assigned to each entry (separated by the separator character). Emissions are always entirely written into the first listed category, while emissions of zero are used for any other assigned category." on [HEMCO user guide](http://wiki.seas.harvard.edu/geos-chem/index.php/The_HEMCO_User%27s_Guide#Base_emissions). I am a little bit concerned and wonder whether it is an useless function? Since no values will go into the cat after the first one, they either do not contribute to GC species or summarised by HEMCO diagnostics? Can you convince me by some simple applications?

Thanks in advance!

Kind regard,
Fei

**Comment by yantosca** [comment]
I have updated the HEMCO User's guide with an explanation.  See the table in this section.
http://wiki.geos-chem.org/The_HEMCO_User%27s_Guide#Base_emissions
