### ISSUE TITLE
[BUG/ISSUE] - Double counting of acetone source from monoterpenes when using online MEGAN

### ISSUE THREAD

**Issue by dylanbm** [geoschem/HEMCO#92]
The online version of the MEGAN biogenic emissions (hcox_megan_mod.F90) includes a parameterized acetone source from monoterpene oxidation (Inst%FLUXACETmo). However our standard model now includes explicit monoterpene treatment in KPP so this is double counting the acetone source from these compounds. All mentions of ACETmo should be removed from hcox_megan_mod.F90.

**Comment by msulprizio** [comment]
Thanks for reporting this @dylanbm! We are currently benchmarking GEOS-Chem 13.2.0, but we will include this fix in GEOS-Chem 13.3.0. Would you mind [submitting a pull request](http://wiki.seas.harvard.edu/geos-chem/index.php/Submitting_updates_for_inclusion_in_GEOS-Chem) with the necessary code updates?

**Comment by msulprizio** [comment]
See https://github.com/geoschem/HEMCO/pull/93

**Comment by msulprizio** [comment]
This has been resolved by PR #93 and is now currently in the `dev` branch. This fix will be included with HEMCO 3.2.0 / GEOS-Chem 13.3.0.
