### ISSUE TITLE
[BUG/ISSUE] 13.1.1 HEMCO Standalone - HEMCO_Config.rc.fullchem template doesn't get filled in properly

### ISSUE THREAD

**Issue by hmhorow** [geoschem/HEMCO#94]
### Description of the problem
I created a HEMCO Standalone run directory from version 13.1.1. When asked, "Enter path to the HEMCO_Config.rc file with your emissions settings. NOTE: This may be a HEMCO_Config.rc file from a GEOS-Chem run directory or a HEMCO_Config.template file from the GEOS-Chem source code repository." I entered the HEMCO_Config.rc.fullchem file from the GCClassic.13.1.1/run/HEMCO_Config.rc.templates/ directory. I didn't modify any of the config files and submitted a 1-month run, where it became clear that the HEMCO_Config.rc file was not updated to reflect the year, meteorological fields chosen, etc. so the file paths to emissions files included variables and the run died as a result with the error message: "HEMCO (VOLCANO): REQUIRED FILE NOT FOUND /projects/horowitz_group/GEOSChem_input_data/ExtData/HEMCO/VOLCANO/v2019-08/{VOLC_YEAR}/07/so2_volcanic_emissions_Carns.20190701.rc" (full log file attached below). The HEMCO_Config.rc file is here: 
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/6874656/HEMCO_Config.rc.txt)

### Description of troubleshooting performed
you can solve the issue by copying a HEMCO_Config.rc file from a real GEOS-Chem run directory. Not sure if this is an issue in 13.1.2. 

### GEOS-Chem version
13.1.1

### Log files
- Run logs (if applicable): 
[HEMCO_SA.log](https://github.com/geoschem/geos-chem/files/6874650/HEMCO_SA.log)

### Software versions
- CMake version: 3.18.4
- Compilers (Intel or GNU, and version): gcc 9.3.0
- NetCDF version: 4.7.4

This is quite minor but it didn't seem to happen with other version of GC. Thanks!

**Comment by yantosca** [comment]
It might be better to use a HEMCO_Config.rc from a GEOS-Chem rundir for now, rather than a template file.  I think that some of the token replacements that would normally get done in the GEOS-Chem rundir creation don't get applied to the HEMCO standalone run dir creation.

**Comment by msulprizio** [comment]
Ideally the HEMCO standalone run directory creation should replace all tokens in a HEMCO configuration template file. Several new tokens (including `VOLC_YEAR`) were introduced in GEOS-Chem 13.1.0 with the introduction of GCAP 2.0. The HEMCO createRunDir.sh script needs to be updated to account for the new tokens. I will look into fixing this.

In the meantime, you can do as Bob suggests and use a HEMCO_Config.rc with tokens already replaced, or you can point to a HEMCO_Config.rc.template file from a version prior to GEOS-Chem 13.1.0.

**Comment by msulprizio** [comment]
Hi @hmhorow. This should now be fixed in commit https://github.com/geoschem/HEMCO/pull/98/commits/d3daf36ac055e8758731326cbfe3ac4f37809b50 (currently in the `bugfixes/HEMCO-config-tokens` branch). We'll include this in our next release.
